// Independent #661 r6 probe. Real PostgreSQL, full schema and real services.
// Only un-ordered query answers are pinned to legal result orders: oldest
// findFirst and newest-first findMany. Existing explicit ordering is unchanged.
// All extra PaymentIntent associations are generated by the real decline
// metadata-fallback path in concurrent, separately held transactions.
import type { Prisma } from '@prisma/client';
import { CheckoutWebhookHandlerService } from '../src/checkout/checkout-webhook-handler.service';
import { StripeConnectApiService } from '../src/connect/stripe-connect-api.service';
import { PurchaseFanoutService } from '../src/packages/purchase-fanout.service';
import { PrismaService } from '../src/prisma.service';
import { bootstrapTestSchema } from './utils/bootstrap-test-schema';
import { resetPublicSchema } from './utils/reset-public-schema';

const url = process.env.MWB3_TEST_DATABASE_URL || '';
const live = url ? describe : describe.skip;
class StripeStub extends StripeConnectApiService {
  status = 'requires_payment_method';
  retrievePaymentIntent = jest.fn(async (id: string) => ({ id, status: this.status }));
}
function legalOrder<T extends object>(client: T): T {
  return new Proxy(client, {
    get(target, key, receiver) {
      const value = Reflect.get(target, key, receiver);
      if (key === 'clientPurchase') {
        return new Proxy(value, {
          get(delegate, method) {
            const original = Reflect.get(delegate, method);
            if (method === 'findFirst' || method === 'findMany') {
              return (args: Prisma.ClientPurchaseFindManyArgs) =>
                original.call(delegate, {
                  ...args,
                  orderBy: args.orderBy ?? { created_at: method === 'findFirst' ? 'asc' : 'desc' },
                });
            }
            return typeof original === 'function' ? original.bind(delegate) : original;
          },
        });
      }
      return typeof value === 'function' ? value.bind(target) : value;
    },
  });
}
function deferred() {
  let open: () => void = () => undefined;
  const opened = new Promise<void>((r) => (open = r));
  return { open, opened };
}
type Ev = { id: string; type: string; data: { object: Record<string, unknown> } };
let seq = 0;
const ev = (type: string, id: string, rest: Record<string, unknown> = {}): Ev => ({
  id: `evt_solr6_${(seq += 1)}`, type, data: { object: { id, ...rest } },
});

live('AUD-SOL-661R6-117: filter the activation owner before applying a read cap', () => {
  let prisma: PrismaService;
  let handler: CheckoutWebhookHandlerService;
  const stripe = new StripeStub();
  const CLIENT = 'solr6-client', COACH = 'solr6-coach', PKG = 'solr6-pkg';
  const txRun = <T>(fn: (tx: Prisma.TransactionClient) => Promise<T>) =>
    prisma.$transaction(fn, { timeout: 60_000, maxWait: 10_000 });
  const deliver = async (e: Ev) => {
    const pre = await handler.prefetchForOuterTx(e);
    return txRun((tx) => handler.handle(e, legalOrder(tx), pre));
  };
  beforeAll(async () => {
    prisma = new PrismaService({
      datasources: { db: { url: `${url}${url.includes('?') ? '&' : '?'}connection_limit=16` } },
    });
    await prisma.$connect();
    await resetPublicSchema(prisma);
    await bootstrapTestSchema(prisma);
    for (const id of [CLIENT, COACH]) {
      await prisma.user.create({
        data: { id, supabase_id: id, email: `${id}@example.test`, name: id },
      });
    }
    await prisma.coachPackage.create({
      data: { id: PKG, coach_id: COACH, name: 'Audit package', amount_cents: 5000 },
    });
    const orderedPrisma = legalOrder(prisma);
    const fanout = new PurchaseFanoutService(undefined, undefined, undefined, orderedPrisma);
    handler = new CheckoutWebhookHandlerService(
      orderedPrisma, stripe, undefined, undefined, undefined, fanout,
    );
  }, 180_000);
  afterAll(async () => {
    if (prisma) await prisma.$disconnect();
  });

  it.each([9, 10])(
    'the activated owner still recovers with %i concurrent never-activated metadata adoptions',
    async (adoptionCount) => {
      stripe.status = 'requires_payment_method';
      const pi = `pi_solr6_${adoptionCount}`;
      const owner = `owner-${adoptionCount}`;
      const baseTime = Date.now();
      const makePending = (id: string, time: number) =>
        prisma.clientPurchase.create({ data: {
          id, client_user_id: CLIENT, coach_user_id: COACH, package_id: PKG,
          amount_cents: 5000, stripe_checkout_session_id: `cs_${id}`,
          stripe_customer_id: 'cus_solr6', idempotency_key: id, created_at: new Date(time),
        } });
      await makePending(owner, baseTime);
      const release = deferred();
      const adopting: Promise<void>[] = [];
      try {
        for (let i = 0; i < adoptionCount; i += 1) {
          const id = `adopted-${adoptionCount}-${i}`;
          await makePending(id, baseTime + i + 1);
          const held = deferred();
          const failed = ev('payment_intent.payment_failed', pi, {
            metadata: { tgp_package_id: PKG, tgp_client_user_id: CLIENT },
          });
          const adoption = txRun(async (tx) => {
            const result = await handler.handle(failed, legalOrder(tx), {});
            expect(result).toEqual({ claimed: true, purchase_id: id });
            held.open();
            await release.opened;
          });
          adopting.push(adoption);
          await Promise.race([held.opened, adoption]);
        }
      } finally {
        release.open();
        await Promise.all(adopting);
      }
      // Genuine owning Checkout completion stamps the same PI on its own row
      // and writes its activation record; none of the adoptions is entitled.
      await deliver(ev('checkout.session.completed', `cs_${owner}`, {
        payment_intent: pi, mode: 'payment', customer: 'cus_solr6',
      }));
      expect(await prisma.purchaseFanout.count({ where: { purchase_id: owner } })).toBe(1);
      await prisma.scheduledDrop.create({ data: {
        id: `drop-${owner}`, client_purchase_id: owner, content_id: owner, asset_type: 'workout',
        asset_id: 'asset', cadence_kind: 'offset_days', cadence_payload: {},
        fire_at: new Date(baseTime + 86_400_000),
      } });
      // An allowed unordered lookup selects the owning, activated purchase.
      await deliver(ev('payment_intent.payment_failed', pi));
      expect(await prisma.clientPurchase.count({
        where: { stripe_payment_intent_id: pi, status: 'payment_failed' },
      })).toBe(adoptionCount + 1);
      expect(await prisma.clientPurchase.count({
        where: { stripe_payment_intent_id: pi, entitlement_active: true },
      })).toBe(0);
      // Success is the behavior under test: the activation owner can be outside
      // the first ten *unfiltered* failed rows.
      stripe.status = 'succeeded';
      const result = await deliver(ev('payment_intent.succeeded', pi));
      const persisted = await prisma.clientPurchase.findUniqueOrThrow({ where: { id: owner } });
      const drop = await prisma.scheduledDrop.findUniqueOrThrow({ where: { id: `drop-${owner}` } });
      expect({ result, status: persisted.status, entitled: persisted.entitlement_active,
        drop: drop.status }).toEqual({
        result: { claimed: true, purchase_id: owner, reason: 'payment_recovered' },
        status: 'paid', entitled: true, drop: 'pending',
      });
      expect(await prisma.clientPurchase.count({
        where: { stripe_payment_intent_id: pi, entitlement_active: true, id: { not: owner } },
      })).toBe(0);
    }, 120_000,
  );
});
