/**
 * P0 schema drift repair: static checks for
 * prisma/migrations/20270125000000_restore_schema_declared_objects.
 *
 * Production failed every User read with "column User.archived_at does not
 * exist" because fields were added to schema.prisma without a migration. The
 * end-to-end proof is CI: migration-dry-run.yml applies the chain and proves
 * down/forward byte-identity, and schema-parity.yml diffs the applied chain
 * against schema.prisma. These static checks run in build-and-test with no
 * database and pin what CI cannot see cheaply: the migration is additive,
 * guarded and transactional; every object it creates matches what
 * schema.prisma declares (column names, nullability, defaults present);
 * the four new tables carry the server-only RLS posture; down.sql removes
 * exactly what the migration adds and nothing else.
 */
import { readFileSync, readdirSync } from 'fs';
import { join } from 'path';

const ROOT = join(__dirname, '..');
const NAME = '20270125000000_restore_schema_declared_objects';
const DIR = join(ROOT, 'prisma', 'migrations', NAME);
const SQL = readFileSync(join(DIR, 'migration.sql'), 'utf8');
const DOWN = readFileSync(join(DIR, 'down.sql'), 'utf8');
const SCHEMA = readFileSync(join(ROOT, 'prisma', 'schema.prisma'), 'utf8');

const NEW_TABLES = ['UserPreferences', 'Recipe', 'SavedRecipe', 'ListItem'] as const;
const NEW_COLUMNS: Record<string, string[]> = {
  User: ['archived_at'],
  UserProfile: [
    'bio',
    'weight_unit',
    'meals_per_day',
    'water_goal_oz',
    'calorie_display',
    'onboardingCompleted',
  ],
  NotificationPreferences: ['daily_checkin_enabled', 'weekly_summary_enabled', 'new_client_alerts'],
};

/** SQL with `--` comment lines removed, so header prose never satisfies an assertion. */
function code(sql: string): string {
  return sql
    .split('\n')
    .filter((l) => !/^\s*--/.test(l))
    .join('\n');
}

const SCALARS = new Set(['String', 'Int', 'Float', 'Boolean', 'DateTime', 'Json', 'Decimal', 'BigInt', 'Bytes']);
const ENUMS = new Set([...SCHEMA.matchAll(/^enum (\w+) \{/gm)].map((m) => m[1]));

interface Field {
  name: string;
  type: string;
  optional: boolean;
  list: boolean;
  hasDefault: boolean;
}

/** Scalar and enum fields of a model block in schema.prisma (relation fields excluded). */
function modelFields(model: string): Field[] {
  const start = SCHEMA.indexOf(`\nmodel ${model} {`);
  if (start < 0) throw new Error(`model ${model} not found in schema.prisma`);
  const end = SCHEMA.indexOf('\n}', start);
  const fields: Field[] = [];
  for (const raw of SCHEMA.slice(start, end).split('\n').slice(2)) {
    const line = raw.replace(/\/\/.*$/, '').trim();
    if (!line || line.startsWith('@@')) continue;
    const m = /^(\w+)\s+(\w+)(\[\])?(\?)?(.*)$/.exec(line);
    if (!m) continue;
    const [, name, type, list, optional, rest] = m;
    if (!SCALARS.has(type) && !ENUMS.has(type)) continue;
    expect(rest).not.toMatch(/@map\(/); // column name == field name for every field checked here
    // uuid()/cuid() defaults are generated by the Prisma client, not the database.
    const hasDefault = /@default\((?!uuid\(|cuid\(|nanoid\()/.test(rest);
    fields.push({ name, type, optional: !!optional, list: !!list, hasDefault });
  }
  return fields;
}

/** Column definitions of `CREATE TABLE IF NOT EXISTS "<t>" (...)` in the migration. */
function createdColumns(table: string): Map<string, string> {
  const m = new RegExp(`CREATE TABLE IF NOT EXISTS "${table}" \\(([\\s\\S]*?)\\n\\);`).exec(code(SQL));
  if (!m) throw new Error(`CREATE TABLE IF NOT EXISTS "${table}" not found`);
  const cols = new Map<string, string>();
  for (const line of m[1].split('\n')) {
    const c = /^\s*"(\w+)" (.*?),?$/.exec(line);
    if (c) cols.set(c[1], c[2]);
  }
  return cols;
}

/** `ADD COLUMN IF NOT EXISTS "<c>" <def>` clauses of `ALTER TABLE "<t>"` in the migration. */
function addedColumns(table: string): Map<string, string> {
  const m = new RegExp(`ALTER TABLE "${table}"([\\s\\S]*?);`).exec(code(SQL));
  if (!m) throw new Error(`ALTER TABLE "${table}" not found`);
  const cols = new Map<string, string>();
  for (const c of m[1].matchAll(/ADD COLUMN IF NOT EXISTS "(\w+)" ([^,]+)/g)) cols.set(c[1], c[2].trim());
  return cols;
}

describe(`${NAME}: placement and transaction`, () => {
  it('sorts after the last migration production has applied, so the next deploy applies it', () => {
    const dirs = readdirSync(join(ROOT, 'prisma', 'migrations'), { withFileTypes: true })
      .filter((e) => e.isDirectory() && /^\d{14}_/.test(e.name))
      .map((e) => e.name)
      .sort();
    expect(dirs).toContain(NAME);
    expect(NAME > '20270124000000_scout_run_observation_expand').toBe(true);
  });

  it('runs in one transaction with bounded lock and statement time', () => {
    const c = code(SQL).trim();
    expect(c.startsWith('BEGIN;')).toBe(true);
    expect(c.endsWith('COMMIT;')).toBe(true);
    expect(c).toContain("SET LOCAL lock_timeout = '5s';");
    expect(c).toContain("SET LOCAL statement_timeout = '30s';");
    expect(c).not.toMatch(/^\s*SET (?!LOCAL)/m);
  });
});

describe(`${NAME}: additive and idempotent`, () => {
  it('contains no destructive or row-rewriting statement', () => {
    const c = code(SQL);
    expect(c).not.toMatch(/\bDROP\s+(TABLE|COLUMN|TYPE|INDEX|CONSTRAINT|SCHEMA|FUNCTION|TRIGGER)\b/i);
    expect(c).not.toMatch(/\b(TRUNCATE\s+(TABLE\s+)?["%]|DELETE\s+FROM|UPDATE\s+"|INSERT\s+INTO)/i);
    expect(c).not.toMatch(/\bALTER\s+COLUMN\b/i);
    expect(c).not.toMatch(/\bRENAME\b/i);
    // The only DROP is the DROP POLICY IF EXISTS that precedes each CREATE POLICY.
    expect(new Set([...c.matchAll(/\bDROP\s+(\w+)/gi)].map((m) => m[1].toUpperCase()))).toEqual(
      new Set(['POLICY']),
    );
  });

  it('guards every create: IF NOT EXISTS, or a catalog check for TYPE and FOREIGN KEY', () => {
    const c = code(SQL);
    expect(c.match(/CREATE TABLE (?!IF NOT EXISTS)/g)).toBeNull();
    expect(c.match(/CREATE (UNIQUE )?INDEX (?!IF NOT EXISTS)/g)).toBeNull();
    expect(c.match(/ADD COLUMN (?!IF NOT EXISTS)/g)).toBeNull();
    expect(c).toMatch(/IF NOT EXISTS \(\s*SELECT 1 FROM pg_catalog\.pg_type[\s\S]*?CREATE TYPE "ListType"/);
    expect(c).toMatch(/IF NOT EXISTS \(\s*SELECT 1 FROM pg_catalog\.pg_constraint[\s\S]*?EXECUTE fk\.ddl;/);
    expect(c.match(/CREATE POLICY/g)?.length).toBe(3); // inside the RLS loop
    expect(c.match(/DROP POLICY IF EXISTS/g)?.length).toBe(3);
  });

  it('asserts the final shape of every object, so a guard cannot skip a wrong pre-existing object', () => {
    const verify = code(SQL).slice(code(SQL).indexOf('DO $verify$'));
    expect(verify).toContain("RAISE EXCEPTION 'restore_schema_declared_objects: objects missing or not in the declared shape");
    for (const [table, cols] of Object.entries(NEW_COLUMNS)) {
      for (const col of cols) expect(verify).toContain(`('${table}', '${col}', `);
    }
    for (const table of NEW_TABLES) {
      for (const col of createdColumns(table).keys()) expect(verify).toContain(`('${table}', '${col}', `);
      expect(verify).toContain(`('${table}', ${createdColumns(table).size})`);
      expect(verify).toContain(`'${table}_pkey', 'p', NULL`);
    }
  });
});

describe(`${NAME}: matches what schema.prisma declares`, () => {
  it.each(NEW_TABLES)('table %s has exactly the scalar fields of its model', (table) => {
    const fields = modelFields(table);
    const cols = createdColumns(table);
    expect([...cols.keys()].sort()).toEqual(fields.map((f) => f.name).sort());
    for (const f of fields) {
      const def = cols.get(f.name) ?? '';
      // Prisma never emits NOT NULL for scalar lists; otherwise NOT NULL iff required.
      expect(def.includes('NOT NULL')).toBe(!f.optional && !f.list);
      expect(def.includes('DEFAULT')).toBe(f.hasDefault);
      if (f.list) expect(def).toMatch(/\[\]/);
      if (ENUMS.has(f.type)) expect(def).toContain(`"${f.type}"`);
    }
  });

  it.each(Object.keys(NEW_COLUMNS))('columns added to %s are declared on the model with matching nullability/defaults', (table) => {
    const fields = new Map(modelFields(table).map((f) => [f.name, f]));
    const added = addedColumns(table);
    expect([...added.keys()].sort()).toEqual([...NEW_COLUMNS[table]].sort());
    for (const [col, def] of added) {
      const f = fields.get(col);
      expect(f).toBeDefined();
      expect(def.includes('NOT NULL')).toBe(!f!.optional);
      expect(def.includes('DEFAULT')).toBe(f!.hasDefault);
    }
  });

  it('creates the ListType enum with the declared labels in order', () => {
    const block = /enum ListType \{([\s\S]*?)\}/.exec(SCHEMA)![1];
    const labels = block
      .split('\n')
      .map((l) => l.replace(/\/\/.*$/, '').trim())
      .filter(Boolean);
    expect(labels).toEqual(['grocery', 'shopping']);
    expect(code(SQL)).toContain(`CREATE TYPE "ListType" AS ENUM ('grocery', 'shopping');`);
  });

  it('declares every foreign key with the Prisma default actions for a required relation', () => {
    const fks = [...code(SQL).matchAll(/ADD CONSTRAINT "(\w+)" FOREIGN KEY \("(\w+)"\) REFERENCES "(\w+)"\("id"\) (ON DELETE \w+ ON UPDATE \w+)/g)];
    expect(fks.map((m) => [m[1], m[2], m[3], m[4]])).toEqual([
      ['UserPreferences_user_id_fkey', 'user_id', 'User', 'ON DELETE RESTRICT ON UPDATE CASCADE'],
      ['Recipe_created_by_id_fkey', 'created_by_id', 'User', 'ON DELETE RESTRICT ON UPDATE CASCADE'],
      ['SavedRecipe_user_id_fkey', 'user_id', 'User', 'ON DELETE RESTRICT ON UPDATE CASCADE'],
      ['SavedRecipe_recipe_id_fkey', 'recipe_id', 'Recipe', 'ON DELETE RESTRICT ON UPDATE CASCADE'],
      ['ListItem_user_id_fkey', 'user_id', 'User', 'ON DELETE RESTRICT ON UPDATE CASCADE'],
    ]);
    // None of these relations declares onDelete, which is what makes RESTRICT correct.
    for (const model of NEW_TABLES) {
      const start = SCHEMA.indexOf(`\nmodel ${model} {`);
      const block = SCHEMA.slice(start, SCHEMA.indexOf('\n}', start));
      expect(block).not.toMatch(/onDelete/);
    }
  });

  it('creates every declared index and unique constraint under its Prisma name', () => {
    const c = code(SQL);
    for (const stmt of [
      'CREATE UNIQUE INDEX IF NOT EXISTS "UserPreferences_user_id_key" ON "UserPreferences"("user_id");',
      'CREATE INDEX IF NOT EXISTS "UserPreferences_user_id_idx" ON "UserPreferences"("user_id");',
      'CREATE INDEX IF NOT EXISTS "Recipe_created_by_id_idx" ON "Recipe"("created_by_id");',
      'CREATE INDEX IF NOT EXISTS "Recipe_is_public_idx" ON "Recipe"("is_public");',
      'CREATE INDEX IF NOT EXISTS "SavedRecipe_user_id_idx" ON "SavedRecipe"("user_id");',
      'CREATE UNIQUE INDEX IF NOT EXISTS "SavedRecipe_user_id_recipe_id_key" ON "SavedRecipe"("user_id", "recipe_id");',
      'CREATE INDEX IF NOT EXISTS "ListItem_user_id_list_type_idx" ON "ListItem"("user_id", "list_type");',
    ]) {
      expect(c).toContain(stmt);
    }
    expect(c.match(/CREATE (UNIQUE )?INDEX/g)?.length).toBe(7);
  });
});

describe(`${NAME}: row-level security on the new tables`, () => {
  const rls = code(SQL).slice(code(SQL).indexOf('DO $rls$'), code(SQL).indexOf('DO $verify$'));

  it('covers exactly the four new tables', () => {
    expect(rls).toContain("FOREACH t IN ARRAY ARRAY['UserPreferences', 'Recipe', 'SavedRecipe', 'ListItem'] LOOP");
  });

  it('enables and forces RLS, grants service_role, denies anon and authenticated, revokes API grants', () => {
    expect(rls).toContain("'ALTER TABLE %I ENABLE ROW LEVEL SECURITY'");
    expect(rls).toContain("'ALTER TABLE %I FORCE ROW LEVEL SECURITY'");
    expect(rls).toContain("'CREATE POLICY %I ON %I AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true)'");
    expect(rls).toContain("'CREATE POLICY %I ON %I AS RESTRICTIVE FOR ALL TO anon USING (false) WITH CHECK (false)'");
    expect(rls).toContain(
      "'CREATE POLICY %I ON %I AS RESTRICTIVE FOR ALL TO authenticated USING (false) WITH CHECK (false)'",
    );
    expect(rls).toContain("'REVOKE ALL PRIVILEGES ON TABLE %I FROM PUBLIC, anon, authenticated'");
    expect(rls).toContain("'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE %I TO service_role'");
    // No permissive policy for an API role and no USING (true) outside service_role.
    expect(rls).not.toMatch(/PERMISSIVE FOR \w+ TO (anon|authenticated|public)/i);
  });

  it('verifies the posture after applying it: policies, and grants per role', () => {
    const verify = code(SQL).slice(code(SQL).indexOf('DO $verify$'));
    expect(verify).toContain('IF r.n_all <> 3 OR r.n_service <> 1 OR r.n_deny <> 2 THEN');
    expect(verify).toContain("AND p.polroles = ARRAY['service_role'::regrole::oid]");
    expect(verify).toContain("pg_catalog.pg_get_expr(p.polqual, p.polrelid) = 'false'");
    for (const rol of ['public', 'anon', 'authenticated']) {
      expect(verify).toContain(`('${rol}', 'SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER', false)`);
    }
    for (const priv of ['SELECT', 'INSERT', 'UPDATE', 'DELETE']) {
      expect(verify).toContain(`('service_role', '${priv}', true)`);
    }
  });

  it('refuses to run where the Supabase API roles are missing', () => {
    expect(code(SQL)).toMatch(/rolname IN \('anon', 'authenticated', 'service_role'\)\) <> 3 THEN\s*RAISE EXCEPTION/);
  });
});

describe(`${NAME}: down.sql`, () => {
  it('removes exactly the objects the migration adds, in one bounded transaction', () => {
    const d = code(DOWN);
    expect(d.trim().startsWith('BEGIN;')).toBe(true);
    expect(d.trim().endsWith('COMMIT;')).toBe(true);
    expect(d).toContain("SET LOCAL lock_timeout = '5s';");
    expect([...d.matchAll(/DROP TABLE IF EXISTS "(\w+)";/g)].map((m) => m[1]).sort()).toEqual([...NEW_TABLES].sort());
    expect([...d.matchAll(/DROP TYPE IF EXISTS "(\w+)";/g)].map((m) => m[1])).toEqual(['ListType']);
    for (const [table, cols] of Object.entries(NEW_COLUMNS)) {
      const m = new RegExp(`ALTER TABLE "${table}"([\\s\\S]*?);`).exec(d);
      expect(m).not.toBeNull();
      expect([...m![1].matchAll(/DROP COLUMN IF EXISTS "(\w+)"/g)].map((x) => x[1]).sort()).toEqual([...cols].sort());
    }
    expect(d.match(/DROP COLUMN/g)?.length).toBe(10);
    expect(d.match(/\bDROP\b/g)?.length).toBe(15);
    expect(d).not.toMatch(/\b(TRUNCATE\s+(TABLE\s+)?["%]|DELETE\s+FROM|UPDATE\s+"|INSERT\s+INTO)/i);
  });

  it('carries the never-run-in-production warning in its header', () => {
    expect(DOWN).toContain('NEVER RUN AGAINST PRODUCTION');
  });
});
