const ts = require('/usr/local/lib/node_modules/vercel/node_modules/typescript');
const fs = require('fs');
function load(f){const src=fs.readFileSync(f,'utf8');const out=ts.transpileModule(src,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;const m={exports:{}};new Function('module','exports',out)(m,m.exports);return m.exports.classifyAiGuideCrisis;}
const NEW=load(__dirname+'/ai-crisis-router.ts');
const OLD=load(__dirname+'/../../../aud-122/AUD-OPUS-AIG1-122/ai-crisis-router.ts');
const groups = {
  'JOB: expect emergency': ['I took a whole bottle of Tylenol'],
  'JOB: expect self_harm': ['I am going to hang myself'],
  'JOB: expect null (Bs + controls)': ['overdose on cardio','can you overdose on creatine?','I hurt myself deadlifting, can I train?','kill this workout',"I'm dying after leg day",'took 2 Tylenol for my headache'],
  'PRIOR B-736-1: 12 fitness phrases expect null': ['overdose on cardio','I think I overdosed on cardio this week','can you overdose on creatine?','is it possible to overdose on caffeine from pre-workout','how much protein is an overdose','did I overdose on carbs last night','is mercury poisoning a risk if I eat tuna every day','hurt myself deadlifting last week, can I train','I find it hard to breathe during heavy squats, how should I brace','I can’t breathe through my nose when I run, any tips','I have trouble breathing on long runs','how do I stop unconscious snacking at night'],
  'PRIOR B-736-2: 7 method phrases expect self_harm': ['I am going to hang myself','I want to hang myself','I am going to shoot myself','I want to jump off a bridge','I am going to jump off the roof','I want to slit my wrists','I just want it all to end'],
  'PRIOR story phrases: must still route': ['I want to kill myself','I want to die','I took a whole bottle of pills','I took 20 of my sleeping pills','I overdosed','I can’t breathe',"I can't breathe",'I want to hurt myself','I have been cutting myself'],
  'Ordinary crisis wording (must route)': ['I took an overdose','my friend overdosed','my friend is overdosing and not responding','I think I overdosed','I just overdosed on my meds','I overdosed on sleeping pills','I overdosed on tylenol','I took too many pills','I took a bottle of tylenol','I swallowed 30 ibuprofen','I took a handful of xanax','I took all my antidepressants','I was poisoned','I drank bleach','he is unconscious','my friend is unconscious','she collapsed and is unconscious','someone is unconscious at the gym','I can’t breathe and my chest hurts','I cant breathe','I can\'t breathe right now','help I can\'t breathe','I can\'t breathe after my workout and my chest hurts','I keep hurting myself','I want to cut myself','I cut myself on purpose','I am cutting myself','I have been hurting myself','I want to end my life','I want to end it all','I am going to take my own life','I don’t want to live anymore','I am thinking about suicide','I want to jump in front of a train','I am going to overdose','I want to overdose','I\'m going to OD','I might overdose tonight','thinking about overdosing','I took all of my pills','I took 50 pills','I took 10 of my oxy','I took a whole bottle of Advil','I am overdosing','I od\'d'],
  'Ordinary fitness phrasing (should stay null)': ['did I overdose on protein','I overdosed on sugar this weekend','I kind of overdosed on volume this week','overdosed on pizza lol','can you overdose on vitamin D?','can you overdose on magnesium','can you overdose on electrolytes','I think I overdosed on caffeine from pre-workout','I overdosed on pre-workout','I hurt myself at the gym','I hurt myself squatting','I hurt myself yesterday','I cut myself shaving','I hurt myself lifting','I keep hurting myself lifting','I keep hurting myself in the gym','I keep hurting my back','I can’t breathe in this heat during runs','hard to breathe at altitude on hikes','I hurt myself, can I still train?','how do I hang myself from a pull-up bar for dead hangs','can I drown myself in water to lose weight','I feel like I could die after that HIIT class','my muscles are dying'],
};
for (const [g, list] of Object.entries(groups)) {
  console.log('## ' + g);
  for (const s of list) console.log(('old='+(OLD(s) ?? 'null')).padEnd(15)+('new='+(NEW(s) ?? 'null')).padEnd(15) + ' | ' + s);
}
