// operator-keys-artifact.spec.ts — locks the CHECKED-IN OPERATOR_KEYS_NEEDED.md
// to committed source and guards the provider→runtime env-name mapping.
//
// The artifact is generated by `scripts/gen-operator-keys.ts` (npm run
// readiness:keys) from the registry + provider-wiring definitions against an
// EMPTY environment, so it is deterministic and truthful without ever reading a
// real secret. These specs fail the build if:
//   - the committed file drifts from freshly-generated content (F-A06);
//   - a provider's required var names diverge from the real runtime names the
//     app reads (e.g. Stripe must use STRIPE_SECRET_KEY / STRIPE_WEBHOOK_SECRET,
//     not an invented PAYMENTS_API_KEY);
//   - the artifact reintroduces the stale example tokens the audit flagged;
//   - the refresh command named in the artifact header is not a real npm script.

import * as fs from 'node:fs';
import * as path from 'node:path';

import { assembleOperatorKeysInput, GENERATION_ENV } from '../../scripts/gen-operator-keys';
import { assertNoDrift, renderOperatorKeysMarkdown } from './operator-keys-generator';
import { PROVIDERS, scanProvidersFromProcess, getProductionBlockers } from './provider-wiring';
import { loadRegistry, getProdRequired } from './registry-loader';

const REPO_ROOT = path.join(__dirname, '..', '..');
const ARTIFACT = path.join(REPO_ROOT, 'OPERATOR_KEYS_NEEDED.md');

/** The fabricated example tokens the audit flagged as stale/untruthful. */
const STALE_EXAMPLE_TOKENS = [
  'PAYMENTS_API_KEY',
  'OBJECT_STORE_BUCKET',
  'TRANSACTIONAL_EMAIL_URL',
  'OBJECT_STORE_REGION',
  'EXAMPLE_NEW_SWITCH',
  'payment-processor',
  'object-storage',
];

describe('OPERATOR_KEYS_NEEDED.md — checked-in artifact', () => {
  it('exists and is not the stale epoch/example artifact', () => {
    expect(fs.existsSync(ARTIFACT)).toBe(true);
    const body = fs.readFileSync(ARTIFACT, 'utf8');
    // The audited artifact carried the Unix-epoch timestamp and example tokens.
    expect(body).not.toContain('1970-01-01T00:00:00.000Z');
    for (const token of STALE_EXAMPLE_TOKENS) {
      expect(body).not.toContain(token);
    }
  });

  it('does not drift from freshly-generated content (F-A06)', async () => {
    const input = await assembleOperatorKeysInput({ repoRoot: REPO_ROOT });
    const { drifted, detail } = assertNoDrift(REPO_ROOT, input);
    expect(detail ?? '').toBe('');
    expect(drifted).toBe(false);
  });

  it('names a real npm script in its refresh instruction', () => {
    const body = fs.readFileSync(ARTIFACT, 'utf8');
    const pkg = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, 'package.json'), 'utf8')) as {
      scripts: Record<string, string>;
    };
    // The header tells the operator how to refresh; that command must exist.
    expect(body).toContain('npm run readiness:keys');
    expect(pkg.scripts['readiness:keys']).toBeDefined();
    expect(pkg.scripts['readiness:keys:check']).toContain('--check');
    // The nonexistent command the audit flagged must be gone.
    expect(body).not.toContain('readiness:check`');
  });
});

describe('operator-keys generation — determinism & secret safety', () => {
  it('generates byte-identical content for a fixed timestamp', async () => {
    const at = '2026-07-23T00:00:00.000Z';
    const a = renderOperatorKeysMarkdown(
      await assembleOperatorKeysInput({ repoRoot: REPO_ROOT, generatedAt: at }),
    );
    const b = renderOperatorKeysMarkdown(
      await assembleOperatorKeysInput({ repoRoot: REPO_ROOT, generatedAt: at }),
    );
    expect(a).toBe(b);
  });

  it('is assembled against an empty env, so no secret value can leak in', () => {
    expect(Object.keys(GENERATION_ENV)).toHaveLength(0);
    const body = fs.readFileSync(ARTIFACT, 'utf8');
    // Every operator-facing command uses the redacted `<value>` placeholder.
    for (const line of body.split('\n').filter((l) => l.includes('fly secrets set'))) {
      expect(line).toContain('=<value>');
    }
  });
});

describe('provider → runtime env-name mapping', () => {
  it('maps Stripe to the real runtime secret names (not a generic payments key)', () => {
    const stripe = PROVIDERS.find((p) => p.id === 'stripe');
    expect(stripe?.requires).toEqual(['STRIPE_SECRET_KEY', 'STRIPE_WEBHOOK_SECRET']);
    expect(stripe?.requires).not.toContain('PAYMENTS_API_KEY');
  });

  it('every provider var in the artifact is a real provider-wiring required var', async () => {
    const input = await assembleOperatorKeysInput({ repoRoot: REPO_ROOT });
    const knownVars = new Set(
      PROVIDERS.flatMap((p) => [...p.requires, ...(p.requiresAnyOf ?? []).flat()]),
    );
    for (const provider of input.providers_stubbed) {
      for (const v of [...provider.env_vars_missing, ...provider.env_vars_placeholder]) {
        expect(knownVars.has(v)).toBe(true);
      }
    }
  });

  it('section 1 switches are exactly the registry MUST_SET rows', async () => {
    const registry = await loadRegistry(path.join(REPO_ROOT, 'prod-switches.yml'));
    const mustSet = getProdRequired(registry).map((r) => r.name);
    const input = await assembleOperatorKeysInput({ repoRoot: REPO_ROOT });
    expect(input.switches_unset_required.map((s) => s.name)).toEqual(mustSet);
  });

  it('lists only providers whose SDK is actually imported (blockers), never NOT_USED', async () => {
    const blockers = getProductionBlockers([
      ...scanProvidersFromProcess(REPO_ROOT, GENERATION_ENV),
    ]);
    const input = await assembleOperatorKeysInput({ repoRoot: REPO_ROOT });
    expect(input.providers_stubbed.map((p) => p.label)).toEqual(blockers.map((b) => b.label));
  });
});
