/**
 * prod-readiness/operator-keys-generator.ts
 *
 * Implements Q9 case 2 ("if something is STUB / NOT WIRED — don't let it
 * ship, add it to a detailed document of 'Operator keys needed'").
 *
 * Writes OPERATOR_KEYS_NEEDED.md at repo root. The file is regenerated
 * end-to-end on every run, never appended, so stale entries don't
 * accumulate. The file IS checked into git so the operator can see the
 * gap during code review without running the test locally.
 */

import * as fs from 'fs';
import * as path from 'path';
import type { SwitchEntry } from './registry-loader';
import type { ProviderReport } from './provider-wiring';

export interface OperatorKeysInput {
  generated_at: string;
  switches_unset_required: SwitchEntry[];
  providers_stubbed: ProviderReport[];
  unregistered_in_code: string[];
}

export function renderOperatorKeysMarkdown(input: OperatorKeysInput): string {
  const out: string[] = [];
  out.push('# Operator keys needed');
  out.push('');
  out.push(`> _Auto-generated by \`test/deploy-readiness.spec.ts\` on ${input.generated_at}._`);
  out.push('> _Do not edit by hand. Re-run \`npm run readiness:check\` to refresh._');
  out.push('');
  out.push('This file lists every env var / provider credential the operator must');
  out.push('provide before the next production deploy. Three sections, three actions:');
  out.push('');

  // Section 1 — registry says MUST_SET, env is unset.
  out.push('## 1. MUST_SET registry switches that are unset');
  if (input.switches_unset_required.length === 0) {
    out.push('_None. Every MUST_SET switch has a value in the current environment._');
  } else {
    out.push('Set each of these in Fly secrets before deploy:');
    out.push('');
    out.push('| Switch | Owner | Tier | Description | Fly command |');
    out.push('|---|---|---|---|---|');
    for (const s of input.switches_unset_required) {
      out.push(`| \`${s.name}\` | ${s.owner} | ${s.tier} | ${escapeMd(s.description).slice(0, 100)} | \`fly secrets set ${s.name}=<value>\` |`);
    }
  }
  out.push('');

  // Section 2 — providers that have an SDK imported but no real key.
  out.push('## 2. Provider SDKs imported but not credentialed');
  if (input.providers_stubbed.length === 0) {
    out.push('_None. Every imported provider has its required env vars set with non-placeholder values._');
  } else {
    out.push('These providers will silently fail or return stub responses until credentialed:');
    out.push('');
    out.push('| Provider | Missing vars | Placeholder vars |');
    out.push('|---|---|---|');
    for (const p of input.providers_stubbed) {
      out.push(`| ${p.label} | ${p.env_vars_missing.map(b).join(', ') || '-'} | ${p.env_vars_placeholder.map(b).join(', ') || '-'} |`);
    }
  }
  out.push('');

  // Section 3 — R108 violation: in code but not in registry.
  out.push('## 3. Env vars referenced in code but absent from `prod-switches.yml` (R108)');
  if (input.unregistered_in_code.length === 0) {
    out.push('_None. Registry covers every `process.env.X` reference under `src/`._');
  } else {
    out.push('Add a row for each of these to `prod-switches.yml`. CI will fail until the registry is up to date (R108).');
    out.push('');
    for (const n of input.unregistered_in_code) out.push(`- \`${n}\``);
  }
  out.push('');

  out.push('---');
  out.push('');
  out.push('## Quick-start: copy these into Fly');
  out.push('');
  out.push('```bash');
  out.push('# Required switches:');
  for (const s of input.switches_unset_required) {
    out.push(`fly secrets set ${s.name}=<value>   # ${s.owner}`);
  }
  out.push('# Provider credentials:');
  for (const p of input.providers_stubbed) {
    for (const v of p.env_vars_missing) out.push(`fly secrets set ${v}=<value>   # ${p.label}`);
  }
  out.push('```');
  out.push('');
  return out.join('\n');
}

export function writeOperatorKeysMarkdown(repoRoot: string, input: OperatorKeysInput): string {
  const target = path.join(repoRoot, 'OPERATOR_KEYS_NEEDED.md');
  fs.writeFileSync(target, renderOperatorKeysMarkdown(input), 'utf8');
  return target;
}

function escapeMd(s: string): string {
  return s.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

function b(s: string): string {
  return `\`${s}\``;
}
