/**
 * prod-readiness/operator-keys-generator.ts
 *
 * Implements Q9 case 2 ("if something is STUB / NOT WIRED — don't let it
 * ship, add it to a detailed document of 'Operator keys needed'").
 *
 * Writes OPERATOR_KEYS_NEEDED.md at repo root. The file is regenerated
 * end-to-end on every run, never appended, so stale entries don't
 * accumulate. The file IS checked into git so the operator can see the
 * gap during code review without running the test locally.
 *
 * Determinism (F-A06 / F-A16): the only volatile part of the document is the
 * `generated_at` timestamp, which lives on a single marker line. The drift
 * check (`assertNoDrift`) strips that one line before comparing committed vs
 * freshly-rendered content, so a fresh run never produces a spurious diff
 * while every other change is caught.
 *
 * Like the reporter, this module is self-contained: it owns the structural
 * `OperatorKeysInput` contract instead of importing concrete result types from
 * the scanners. The orchestrator passes plain data shapes (including the active
 * stub-pattern inventory) so this generator can land and be reviewed without
 * `stub-scanner`, `provider-wiring`, `auto-flipper`, or `env-discovery` being
 * present on the same branch.
 */

import * as fs from 'fs';
import * as path from 'path';

/** Marker prefix for the single volatile (timestamp) line, stripped on diff. */
export const GENERATED_AT_MARKER = '> _Generated at:';

/**
 * Registry-derived view of a switch the operator must set. A subset of H4.A's
 * `RegistryRow`, declared locally to avoid coupling to the full row type.
 */
export interface SwitchEntry {
  /** Registry switch name (UPPER_SNAKE_CASE). */
  name: string;
  /** Lifecycle tier: hard | prod | feature | optional. */
  tier: string;
  /** Owning domain/team for the switch. */
  owner: string;
  /** One-line human description of what the switch controls. */
  description: string;
}

/**
 * Per-provider wiring report (subset used by this generator): a provider whose
 * SDK is imported but whose credentials are missing or still placeholders.
 */
export interface ProviderReport {
  /** Human-readable provider name shown in tables. */
  label: string;
  /** Required vars with no value in the inspected environment. */
  env_vars_missing: string[];
  /** Required vars whose value is a recognised placeholder/stub. */
  env_vars_placeholder: string[];
}

/** Outcome of one auto-flip the runner applied this run (F-A03). */
export interface AppliedFlip {
  /** Registry switch name that was flipped. */
  name: string;
  /** Whether the flip succeeded. */
  ok: boolean;
  /** Error detail when `ok` is false; omitted on success. */
  error?: string;
}

/** Per-var source attribution gathered by env discovery (F-B19). */
export interface EnvVarOrigin {
  /** Present in the ENV_RULES table. */
  inEnvRules: boolean;
  /** Present in `.env.example`. */
  inEnvExample: boolean;
  /** Referenced somewhere under `src/`. */
  inCode: boolean;
}

/** One stub-scanner pattern, surfaced so operators see exactly what is scanned. */
export interface StubPattern {
  /** The literal token the scanner matches (may contain spaces). */
  token: string;
  /** Severity assigned to a hit on this token by default. */
  defaultSeverity: string;
  /** Human-readable explanation of why the token is treated as a stub. */
  intent: string;
}

/**
 * The scanner-agnostic input the orchestrator (H4.H) assembles for the
 * generator. Every field is a plain data shape so any producer — real scanner
 * or test fixture — can satisfy it without importing this file.
 *
 * Field contract:
 * - `generated_at` — ISO-8601 timestamp written on the volatile marker line.
 * - `switches_unset_required` — MUST_SET switches with no value in the env.
 * - `providers_stubbed` — providers imported but not yet credentialed.
 * - `unregistered_in_code` — env vars in code but absent from the registry.
 * - `applied_flips` — auto-flip outcomes this run; section omitted if empty.
 * - `env_origins` — per-var source attribution; section omitted if absent.
 * - `stub_patterns` — the active scanner pattern inventory; section omitted if
 *   absent. Passed in (rather than imported) so the generator stays decoupled
 *   from the stub scanner.
 */
export interface OperatorKeysInput {
  generated_at: string;
  switches_unset_required: SwitchEntry[];
  providers_stubbed: ProviderReport[];
  unregistered_in_code: string[];
  applied_flips?: AppliedFlip[];
  env_origins?: Map<string, EnvVarOrigin>;
  stub_patterns?: StubPattern[];
}

export function renderOperatorKeysMarkdown(input: OperatorKeysInput): string {
  const out: string[] = [];
  out.push('# Operator keys needed');
  out.push('');
  out.push(`${GENERATED_AT_MARKER} ${input.generated_at}_`);
  out.push('> _Auto-generated by `test/deploy-readiness.spec.ts`. Do not edit by hand;');
  out.push('> re-run `npm run readiness:check` to refresh._');
  out.push('');
  out.push('This file lists every env var / provider credential the operator must');
  out.push('provide before the next production deploy. Three sections, three actions:');
  out.push('');

  // Section 1 — registry says MUST_SET, env is unset.
  out.push('## 1. MUST_SET registry switches that are unset');
  if (input.switches_unset_required.length === 0) {
    out.push('_None. Every MUST_SET switch has a value in the current environment._');
  } else {
    out.push('Set each of these in Fly secrets before deploy:');
    out.push('');
    out.push('| Switch | Owner | Tier | Description | Fly command |');
    out.push('|---|---|---|---|---|');
    for (const s of input.switches_unset_required) {
      out.push(`| \`${s.name}\` | ${s.owner} | ${s.tier} | ${escapeMd(s.description).slice(0, 100)} | \`fly secrets set ${s.name}=<value>\` |`);
    }
  }
  out.push('');

  // Section 2 — providers that have an SDK imported but no real key.
  out.push('## 2. Provider SDKs imported but not credentialed');
  if (input.providers_stubbed.length === 0) {
    out.push('_None. Every imported provider has its required env vars set with non-placeholder values._');
  } else {
    out.push('These providers will silently fail or return stub responses until credentialed:');
    out.push('');
    out.push('| Provider | Missing vars | Placeholder vars |');
    out.push('|---|---|---|');
    for (const p of input.providers_stubbed) {
      out.push(`| ${escapeMd(p.label)} | ${p.env_vars_missing.map(b).join(', ') || '-'} | ${p.env_vars_placeholder.map(b).join(', ') || '-'} |`);
    }
  }
  out.push('');

  // Section 3 — R108 violation: in code but not in registry.
  out.push('## 3. Env vars referenced in code but absent from `prod-switches.yml` (R108)');
  if (input.unregistered_in_code.length === 0) {
    out.push('_None. Registry covers every `process.env.X` reference under `src/`._');
  } else {
    out.push('Add a row for each of these to `prod-switches.yml`. CI will fail until the registry is up to date (R108).');
    out.push('');
    for (const n of input.unregistered_in_code) out.push(`- \`${n}\``);
  }
  out.push('');

  // Section 4 — auto-flips applied this run (F-A03). Omitted if zero.
  if (input.applied_flips && input.applied_flips.length > 0) {
    out.push('## 4. Switches auto-flipped this run');
    out.push('');
    out.push('| Switch | Status | Error |');
    out.push('|---|---|---|');
    for (const f of input.applied_flips) {
      out.push(`| \`${f.name}\` | ${f.ok ? 'applied' : 'FAILED'} | ${f.error ? escapeMd(f.error) : '-'} |`);
    }
    out.push('');
  }

  // Section 5 — env-var source attribution (F-B19). Omitted if not provided.
  if (input.env_origins && input.env_origins.size > 0) {
    out.push('## 5. Env-var source attribution');
    out.push('');
    out.push('Where each discovered env var comes from. A var in code but not in');
    out.push('`.env.example` has no documented default — provide one before launch.');
    out.push('');
    out.push('| Var | ENV_RULES | .env.example | code |');
    out.push('|---|---|---|---|');
    for (const name of [...input.env_origins.keys()].sort()) {
      const o = input.env_origins.get(name)!;
      out.push(`| \`${name}\` | ${o.inEnvRules ? 'Y' : '-'} | ${o.inEnvExample ? 'Y' : '-'} | ${o.inCode ? 'Y' : '-'} |`);
    }
    out.push('');
  }

  // Section 6 — the active stub-scanner pattern list (F-B09). Omitted if the
  // orchestrator did not pass an inventory.
  if (input.stub_patterns && input.stub_patterns.length > 0) {
    out.push('## 6. Active stub-scanner patterns');
    out.push('');
    out.push('These are the tokens the deploy-readiness scanner treats as stub/');
    out.push('placeholder markers in `src/` outside exempt zones. Multi-word tokens');
    out.push('are shown with a middle-dot (`\u00b7`) standing in for the space so this');
    out.push('inventory can itself never trip the very scanner that reads `src/`.');
    out.push('');
    out.push('| Token | Default severity | Intent |');
    out.push('|---|---|---|');
    for (const p of input.stub_patterns) {
      out.push(`| \`${escapeMd(displaySafeToken(p.token))}\` | ${p.defaultSeverity} | ${escapeMd(p.intent)} |`);
    }
    out.push('');
  }

  out.push('---');
  out.push('');
  out.push('## Quick-start: copy these into Fly');
  out.push('');
  out.push('```bash');
  out.push('# Required switches:');
  for (const s of input.switches_unset_required) {
    out.push(`fly secrets set ${s.name}=<value>   # ${s.owner}`);
  }
  out.push('# Provider credentials:');
  for (const p of input.providers_stubbed) {
    for (const v of p.env_vars_missing) out.push(`fly secrets set ${v}=<value>   # ${p.label}`);
  }
  out.push('```');
  out.push('');
  return out.join('\n');
}

export function writeOperatorKeysMarkdown(repoRoot: string, input: OperatorKeysInput): string {
  const target = path.join(repoRoot, 'OPERATOR_KEYS_NEEDED.md');
  const content = renderOperatorKeysMarkdown(input);
  // Atomic write: render to a sibling temp file, then rename over the target so
  // a crash mid-write can never leave a half-written document on disk.
  const tmp = path.join(repoRoot, `.OPERATOR_KEYS_NEEDED.md.${process.pid}.tmp`);
  fs.writeFileSync(tmp, content, 'utf8');
  fs.renameSync(tmp, target);
  return target;
}

/**
 * Strip the single volatile timestamp line so committed vs runtime content can
 * be diffed deterministically (F-A06 / F-A16).
 */
export function stripVolatile(markdown: string): string {
  return markdown
    .split('\n')
    .filter((line) => !line.startsWith(GENERATED_AT_MARKER))
    .join('\n');
}

/**
 * Drift check: returns drifted=true if the committed OPERATOR_KEYS_NEEDED.md
 * (minus the timestamp line) differs from freshly-rendered content. Called by
 * the spec so a stale committed file fails the build (F-A06).
 */
export function assertNoDrift(repoRoot: string, input: OperatorKeysInput): { drifted: boolean; detail?: string } {
  const target = path.join(repoRoot, 'OPERATOR_KEYS_NEEDED.md');
  const fresh = stripVolatile(renderOperatorKeysMarkdown(input));
  if (!fs.existsSync(target)) {
    return { drifted: true, detail: 'OPERATOR_KEYS_NEEDED.md is missing on disk' };
  }
  const committed = stripVolatile(fs.readFileSync(target, 'utf8'));
  if (committed !== fresh) {
    return { drifted: true, detail: 'committed OPERATOR_KEYS_NEEDED.md differs from freshly-generated content (excluding timestamp)' };
  }
  return { drifted: false };
}

function escapeMd(s: string): string {
  return s.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

/**
 * Render a scanner token for display without reproducing any multi-word
 * placeholder literal verbatim (R75): the inner space is replaced with a
 * middle dot so the generated artifact never contains a banned token sequence
 * that the scanner would itself flag. Single-word tokens pass through.
 */
function displaySafeToken(token: string): string {
  return token.replace(/ /g, '\u00b7');
}

function b(s: string): string {
  return `\`${s}\``;
}
