// scorecard-pdf.ts — branded PDF builder for the transformation scorecard.
//
// Uses pdfkit (zero browser dependency, no Chromium download). Layout:
//   - Bone (#F5F1E8) background page
//   - Header bar in oxblood (#4A0404) with TGP wordmark
//   - "Transformation Scorecard" subtitle, client name + date range
//   - "Transformation Momentum: X/100" as a prominent metric
//   - Three section blocks: Body, Income / Engagement, Finance
//     Each block: bold section label + horizontal progress bar + data table
//   - Footer: "Generated by The Growth Project Operator OS"
//
// Fonts: Helvetica (Cormorant Garamond and Inter are not bundled with
// pdfkit's built-in font set). We approximate the brand feel with
// Helvetica-Oblique for display headings and Helvetica for body copy.
// If the project later bundles the actual font files via `pdfkit` font
// registration, swap the font strings here.
//
// Color palette:
//   bone    = #F5F1E8  (page background, light cells)
//   ink     = #1A1A1A  (primary text)
//   oxblood = #4A0404  (header bar, section labels, accent bars)
//   mid     = #888888  (sub-labels, progress bar track)
//   white   = #FFFFFF  (header text)
//
// Stream contract: callers pipe the returned PDFDocument stream directly
// into the Express Response. No temp files on disk.

import type { TransformationScorecardRow } from './transformation-scorecard.service';

// pdfkit is a CommonJS module. We import it via require so TypeScript does
// not need @types/pdfkit to compile. The runtime type below captures the
// surface we actually call.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const PDFDocument = require('pdfkit') as new (opts: {
  size: string;
  margin: number;
  bufferPages?: boolean;
  info?: Record<string, string>;
}) => PDFKit;

// Minimal type surface for the PDFDocument instance we need.
interface PDFKit {
  pipe(dest: NodeJS.WritableStream): this;
  end(): void;
  on(event: string, cb: (...args: unknown[]) => void): this;
  rect(x: number, y: number, w: number, h: number): this;
  fill(color: string): this;
  stroke(color: string): this;
  fillColor(color: string): this;
  fontSize(size: number): this;
  font(name: string): this;
  text(
    text: string,
    xOrOptions?: number | TextOptions,
    yOrOptions?: number | TextOptions,
    opts?: TextOptions,
  ): this;
  moveDown(lines?: number): this;
  moveTo(x: number, y: number): this;
  lineTo(x: number, y: number): this;
  lineWidth(w: number): this;
  save(): this;
  restore(): this;
  roundedRect(x: number, y: number, w: number, h: number, r: number): this;
  y: number;
  page: { width: number; height: number; margins: { top: number; bottom: number; left: number; right: number } };
  addPage(): this;
}

interface TextOptions {
  align?: 'left' | 'center' | 'right';
  width?: number;
  continued?: boolean;
  lineGap?: number;
  underline?: boolean;
}

// Brand palette
const BONE = '#F5F1E8';
const INK = '#1A1A1A';
const OXBLOOD = '#4A0404';
const MID = '#888888';
const WHITE = '#FFFFFF';

const MARGIN = 48;
const CONTENT_WIDTH = 595 - MARGIN * 2; // A4 width – margins

export function buildScorecardPdf(
  rows: TransformationScorecardRow[],
  opts: { clientName?: string; since?: string; generatedAt?: string } = {},
): InstanceType<typeof PDFDocument> {
  const doc = new PDFDocument({
    size: 'A4',
    margin: MARGIN,
    bufferPages: true,
    info: {
      Title: 'Transformation Scorecard',
      Author: 'The Growth Project Operator OS',
      Creator: 'growth-project-backend',
    },
  });

  const reportDate = opts.generatedAt
    ? opts.generatedAt.slice(0, 10)
    : new Date().toISOString().slice(0, 10);

  for (let i = 0; i < rows.length; i++) {
    if (i > 0) doc.addPage();
    renderPageBg(doc);
    renderHeaderBar(doc, reportDate);
    renderClientPage(doc, rows[i], opts.since);
    renderFooter(doc);
  }

  doc.end();
  return doc;
}

// ─── Page background ───────────────────────────────────────────────────────

function renderPageBg(doc: PDFKit): void {
  doc
    .save()
    .rect(0, 0, doc.page.width, doc.page.height)
    .fill(BONE)
    .restore();
}

// ─── Header bar ─────────────────────────────────────────────────────────────

function renderHeaderBar(doc: PDFKit, reportDate: string): void {
  const barH = 56;
  doc
    .save()
    .rect(0, 0, doc.page.width, barH)
    .fill(OXBLOOD)
    .restore();

  // TGP wordmark (text — no raster image dependency)
  doc
    .save()
    .font('Helvetica-Bold')
    .fontSize(18)
    .fillColor(WHITE)
    .text('TGP', MARGIN, 18, { align: 'left', width: 80 })
    .restore();

  // Report title + date in header
  doc
    .save()
    .font('Helvetica-Oblique')
    .fontSize(11)
    .fillColor(WHITE)
    .text('Transformation Scorecard', MARGIN + 48, 20, {
      align: 'left',
      width: CONTENT_WIDTH - 100,
    })
    .restore();

  doc
    .save()
    .font('Helvetica')
    .fontSize(9)
    .fillColor(WHITE)
    .text(reportDate, 0, 22, { align: 'right', width: doc.page.width - MARGIN })
    .restore();
}

// ─── Footer ──────────────────────────────────────────────────────────────────

function renderFooter(doc: PDFKit): void {
  const footerY = doc.page.height - doc.page.margins.bottom - 18;
  doc
    .save()
    .font('Helvetica')
    .fontSize(7)
    .fillColor(MID)
    .text(
      'Generated by The Growth Project Operator OS',
      MARGIN,
      footerY,
      { align: 'center', width: CONTENT_WIDTH },
    )
    .restore();
}

// ─── Per-client page ─────────────────────────────────────────────────────────

function renderClientPage(
  doc: PDFKit,
  row: TransformationScorecardRow,
  since: string | undefined,
): void {
  let y = 72; // below header bar

  // ── Client identity block ───────────────────────────────────────────────
  doc
    .font('Helvetica-Bold')
    .fontSize(15)
    .fillColor(INK)
    .text(row.name || row.email, MARGIN, y, { width: CONTENT_WIDTH });
  y += 22;

  doc
    .font('Helvetica')
    .fontSize(9)
    .fillColor(MID)
    .text(
      [
        row.email,
        row.coach_email ? `Coach: ${row.coach_email}` : null,
        since ? `Window: ${since}` : null,
      ]
        .filter(Boolean)
        .join('   ·   '),
      MARGIN,
      y,
      { width: CONTENT_WIDTH },
    );
  y += 20;

  // ── Transformation Momentum ─────────────────────────────────────────────
  const momentum = computeMomentum(row);
  const momentumDisplay = momentum !== null ? `${momentum}/100` : '—/100';

  doc
    .save()
    .roundedRect(MARGIN, y, CONTENT_WIDTH, 44, 4)
    .fill(OXBLOOD)
    .restore();

  doc
    .font('Helvetica')
    .fontSize(8)
    .fillColor(WHITE)
    .text('TRANSFORMATION MOMENTUM', MARGIN + 12, y + 8, {
      width: CONTENT_WIDTH / 2,
    });

  doc
    .font('Helvetica-Bold')
    .fontSize(22)
    .fillColor(WHITE)
    .text(momentumDisplay, MARGIN + 12, y + 17, {
      width: CONTENT_WIDTH / 2,
    });

  if (row.ptm_bucket) {
    doc
      .font('Helvetica')
      .fontSize(9)
      .fillColor(WHITE)
      .text(
        `Risk bucket: ${row.ptm_bucket.toUpperCase()}`,
        MARGIN + CONTENT_WIDTH / 2,
        y + 18,
        { align: 'right', width: CONTENT_WIDTH / 2 - 12 },
      );
  }
  y += 56;

  // ── Section: Body ───────────────────────────────────────────────────────
  y = renderSection(doc, y, 'BODY', [
    { label: 'Starting weight', value: formatLbs(row.starting_weight_lbs) },
    { label: 'Current weight', value: formatLbs(row.current_weight_lbs) },
    { label: 'Weight delta', value: formatLbs(row.weight_delta_lbs) },
    { label: 'Workout volume (30d)', value: row.workout_volume_30d > 0 ? `${row.workout_volume_30d} lbs` : '—' },
    { label: 'Mood (latest)', value: row.latest_mood !== null ? String(row.latest_mood) : '—' },
    { label: 'Energy (latest)', value: row.latest_energy !== null ? String(row.latest_energy) : '—' },
    { label: 'Sleep hrs (latest)', value: row.latest_sleep_hrs !== null ? String(row.latest_sleep_hrs) : '—' },
  ], progressBarValue(row.weight_delta_lbs !== null ? 1 : 0, 1));

  // ── Section: Income & Engagement ────────────────────────────────────────
  y = renderSection(doc, y, 'INCOME & ENGAGEMENT', [
    { label: 'Days active', value: String(row.days_active) },
    { label: 'Meals logged (30d)', value: String(row.meals_logged_30d) },
    { label: 'Meal consistency', value: `${row.meal_consistency_pct_30d}%` },
    { label: 'Messages sent (30d)', value: String(row.messages_sent_30d) },
    { label: 'Messages received (30d)', value: String(row.messages_received_30d) },
    { label: 'Build week status', value: row.build_week_status ?? '—' },
    { label: 'Diagnostic score', value: row.diagnostic_overall_score !== null ? `${row.diagnostic_overall_score} (${row.diagnostic_bucket ?? ''})` : '—' },
  ], progressBarValue(row.meal_consistency_pct_30d, 100));

  // ── Section: Finance & PTM ───────────────────────────────────────────────
  y = renderSection(doc, y, 'FINANCE & PTM', [
    { label: 'PTM risk score', value: row.ptm_risk_score !== null ? row.ptm_risk_score.toFixed(2) : '—' },
    { label: 'PTM success score', value: row.ptm_success_score !== null ? row.ptm_success_score.toFixed(2) : '—' },
    { label: 'Latest outcome', value: row.latest_outcome ?? '—' },
    { label: 'Wealth velocity score', value: row.wealth_velocity_score !== null ? row.wealth_velocity_score.toFixed(1) : '—' },
    { label: 'Net worth delta', value: row.net_worth_delta !== null ? `£${row.net_worth_delta.toLocaleString()}` : '—' },
    { label: 'Milestones hit', value: row.milestones_hit !== null ? String(row.milestones_hit) : '—' },
  ], progressBarValue(row.ptm_success_score ?? 0, 1));
}

// ─── Section renderer ────────────────────────────────────────────────────────

function renderSection(
  doc: PDFKit,
  startY: number,
  title: string,
  rows: Array<{ label: string; value: string }>,
  progressFraction: number,
): number {
  let y = startY;

  // Section label
  doc
    .font('Helvetica-Bold')
    .fontSize(8)
    .fillColor(OXBLOOD)
    .text(title, MARGIN, y, { width: CONTENT_WIDTH });
  y += 14;

  // Progress bar track
  const trackW = CONTENT_WIDTH;
  const trackH = 5;
  doc
    .save()
    .roundedRect(MARGIN, y, trackW, trackH, 2)
    .fill(MID)
    .restore();

  // Progress bar fill
  const fillW = Math.max(0, Math.min(1, progressFraction)) * trackW;
  if (fillW > 0) {
    doc
      .save()
      .roundedRect(MARGIN, y, fillW, trackH, 2)
      .fill(OXBLOOD)
      .restore();
  }
  y += trackH + 10;

  // Data rows (two-column label / value table)
  const COL_LABEL_W = 170;
  const COL_VALUE_W = CONTENT_WIDTH - COL_LABEL_W - 20;

  for (const r of rows) {
    doc
      .font('Helvetica')
      .fontSize(8)
      .fillColor(MID)
      .text(r.label, MARGIN, y, { width: COL_LABEL_W });

    doc
      .font('Helvetica')
      .fontSize(8)
      .fillColor(INK)
      .text(r.value, MARGIN + COL_LABEL_W + 20, y, { width: COL_VALUE_W });

    y += 13;
  }

  y += 10; // section gap

  // Light separator line
  doc
    .save()
    .moveTo(MARGIN, y)
    .lineTo(MARGIN + CONTENT_WIDTH, y)
    .lineWidth(0.5)
    .stroke('#D6D1C4')
    .restore();

  y += 10;
  return y;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function computeMomentum(row: TransformationScorecardRow): number | null {
  // Transformation Momentum = 100 – (ptm_risk_score * 100), rounded to
  // nearest integer. This maps 0.0 risk → 100/100 and 1.0 risk → 0/100.
  // When the score is unavailable (null) we return null.
  if (row.ptm_risk_score === null) return null;
  return Math.round((1 - row.ptm_risk_score) * 100);
}

function progressBarValue(value: number, max: number): number {
  if (!Number.isFinite(value) || !Number.isFinite(max) || max === 0) return 0;
  return Math.min(1, Math.max(0, value / max));
}

function formatLbs(value: number | null): string {
  if (value === null) return '—';
  return `${value} lbs`;
}
