// Independent #661 r6 probe. Real PostgreSQL, full schema and real services.
// Only un-ordered query answers are pinned to legal result orders: oldest
// findFirst and newest-first findMany. Existing explicit ordering is unchanged.
// All extra PaymentIntent associations are generated by the real decline
// metadata-fallback path in concurrent, separately held transactions.
import type { Prisma } from '@prisma/client';
import { CheckoutWebhookHandlerService } from '../src/checkout/checkout-webhook-handler.service';
import { CheckoutService } from '../src/checkout/checkout.service';
import { StripeConnectApiService } from '../src/connect/stripe-connect-api.service';
import { PurchaseFanoutService } from '../src/packages/purchase-fanout.service';
import { PrismaService } from '../src/prisma.service';
import { bootstrapTestSchema } from './utils/bootstrap-test-schema';
import { resetPublicSchema } from './utils/reset-public-schema';

const url = process.env.MWB3_TEST_DATABASE_URL || '';
const live = url ? describe : describe.skip;
class StripeStub extends StripeConnectApiService {
  status = 'requires_payment_method';
  retrievePaymentIntent = jest.fn(async (id: string) => ({ id, status: this.status }));
  createPaymentIntent = jest.fn(async (
    _args: Parameters<StripeConnectApiService['createPaymentIntent']>[0],
  ) => ({ id: 'pi_unused', client_secret: 'pi_unused_secret_test' }));
  createEphemeralKey = jest.fn(async () => ({ secret: 'ek_test_solr6' }));
}
function wiring<T>(value: object): T { return value as T; }
function legalOrder<T extends { clientPurchase: Prisma.TransactionClient['clientPurchase'] }>(
  client: T,
): T {
  return new Proxy(client, {
    get(target, key, receiver) {
      const value = Reflect.get(target, key, receiver);
      if (key === 'clientPurchase') {
        return new Proxy(target.clientPurchase, {
          get(delegate, method) {
            const original = Reflect.get(delegate, method);
            if (method === 'findFirst' || method === 'findMany') {
              return (args: Prisma.ClientPurchaseFindManyArgs) =>
                original.call(delegate, {
                  ...args,
                  orderBy: args.orderBy ?? { created_at: method === 'findFirst' ? 'asc' : 'desc' },
                });
            }
            return typeof original === 'function' ? original.bind(delegate) : original;
          },
        });
      }
      return typeof value === 'function' ? value.bind(target) : value;
    },
  });
}
function deferred() {
  let open: () => void = () => undefined;
  const opened = new Promise<void>((r) => (open = r));
  return { open, opened };
}
type Ev = { id: string; type: string; data: { object: Record<string, unknown> } };
let seq = 0;
const ev = (type: string, id: string, rest: Record<string, unknown> = {}): Ev => ({
  id: `evt_solr6_${(seq += 1)}`, type, data: { object: { id, ...rest } },
});

live('AUD-SOL-661R6-117: filter the activation owner before applying a read cap', () => {
  let prisma: PrismaService;
  let handler: CheckoutWebhookHandlerService;
  let checkout: CheckoutService;
  const stripe = new StripeStub();
  const CLIENT = 'solr6-client', COACH = 'solr6-coach', PKG = 'solr6-pkg';
  const txRun = <T>(fn: (tx: Prisma.TransactionClient) => Promise<T>) =>
    prisma.$transaction(fn, { timeout: 60_000, maxWait: 10_000 });
  const deliver = async (e: Ev) => {
    const pre = await handler.prefetchForOuterTx(e);
    return txRun((tx) => handler.handle(e, legalOrder(tx), pre));
  };
  beforeAll(async () => {
    prisma = new PrismaService({
      datasources: { db: { url: `${url}${url.includes('?') ? '&' : '?'}connection_limit=16` } },
    });
    await prisma.$connect();
    await resetPublicSchema(prisma);
    await bootstrapTestSchema(prisma);
    for (const id of [CLIENT, COACH]) {
      await prisma.user.create({
        data: { id, supabase_id: id, email: `${id}@example.test`, name: id },
      });
    }
    await prisma.coachPackage.create({
      data: { id: PKG, coach_id: COACH, name: 'Audit package', amount_cents: 5000,
        published_at: new Date() },
    });
    await prisma.user.update({ where: { id: CLIENT }, data: { coach_id: COACH } });
    await prisma.connectAccount.create({
      data: { coach_user_id: COACH, stripe_account_id: 'acct_solr6', charges_enabled: true },
    });
    await prisma.connectCustomer.create({
      data: { client_user_id: CLIENT, stripe_customer_id: 'cus_solr6' },
    });
    const orderedPrisma = legalOrder(prisma);
    const fanout = new PurchaseFanoutService(undefined, undefined, undefined, orderedPrisma);
    handler = new CheckoutWebhookHandlerService(
      orderedPrisma, stripe, undefined, undefined, undefined, fanout,
    );
    type C = ConstructorParameters<typeof CheckoutService>;
    checkout = new CheckoutService(
      prisma, stripe,
      wiring<C[2]>({ getById: (id: string) => prisma.coachPackage.findUnique({ where: { id } }) }),
      wiring<C[3]>({ ready: true, reason: null }),
      wiring<C[4]>({ planFor: async () => ({
        application_fee_cents: 100, head_coach_split_cents: 0,
      }) }),
      wiring<C[5]>({ evaluate: async () => ({ ok: true }) }),
    );
  }, 180_000);
  afterAll(async () => {
    if (prisma) await prisma.$disconnect();
  });

  it.each([9, 10])(
    'the activated owner still recovers with %i concurrent real PaymentSheet reservations adopted by declines',
    async (adoptionCount) => {
      stripe.status = 'requires_payment_method';
      const pi = `pi_solr6_${adoptionCount}`;
      const owner = `owner-${adoptionCount}`;
      const baseTime = Date.now();
      const makePending = (id: string, time: number) =>
        prisma.clientPurchase.create({ data: {
          id, client_user_id: CLIENT, coach_user_id: COACH, package_id: PKG,
          amount_cents: 5000, stripe_checkout_session_id: `cs_${id}`,
          stripe_customer_id: 'cus_solr6', idempotency_key: id, created_at: new Date(time),
        } });
      await makePending(owner, baseTime);
      const release = deferred();
      const releaseMint = deferred();
      const adopting: Promise<void>[] = [];
      const creating: Array<ReturnType<CheckoutService['createPaymentIntentForClient']>> = [];
      try {
        for (let i = 0; i < adoptionCount; i += 1) {
          const minted = deferred();
          const key = `00000000-0000-4000-8000-${String(adoptionCount * 100 + i).padStart(12, '0')}`;
          stripe.createPaymentIntent.mockImplementationOnce(async () => {
            minted.open();
            await releaseMint.opened;
            return { id: `pi_other_${adoptionCount}_${i}`, client_secret: 'pi_other_secret_test' };
          });
          const create = checkout.createPaymentIntentForClient(CLIENT, {
            package_id: PKG, idempotency_key: key,
          });
          creating.push(create);
          await Promise.race([minted.opened, create]);
          const reserved = await prisma.clientPurchase.findUniqueOrThrow({
            where: { idempotency_key: `pi-${CLIENT}-${key}` },
          });
          const id = reserved.id;
          expect(reserved).toMatchObject({
            status: 'pending', stripe_payment_intent_id: null,
            stripe_checkout_session_id: `pi-reserved-pi-${CLIENT}-${key}`,
          });
          const held = deferred();
          const failed = ev('payment_intent.payment_failed', pi, {
            metadata: { tgp_package_id: PKG, tgp_client_user_id: CLIENT },
          });
          const adoption = txRun(async (tx) => {
            const result = await handler.handle(failed, legalOrder(tx), {});
            expect(result).toEqual({ claimed: true, purchase_id: id });
            held.open();
            await release.opened;
          });
          adopting.push(adoption);
          await Promise.race([held.opened, adoption]);
        }
        release.open();
        await Promise.all(adopting);
        // Owning completion and failure run through the real handler while
        // the unrelated native requests are still awaiting provider replies.
        await deliver(ev('checkout.session.completed', `cs_${owner}`, {
          payment_intent: pi, mode: 'payment', customer: 'cus_solr6',
        }));
        expect(await prisma.purchaseFanout.count({ where: { purchase_id: owner } })).toBe(1);
        await prisma.scheduledDrop.create({ data: {
          id: `drop-${owner}`, client_purchase_id: owner, content_id: owner, asset_type: 'workout',
          asset_id: 'asset', cadence_kind: 'offset_days', cadence_payload: {},
          fire_at: new Date(baseTime + 86_400_000),
        } });
        await deliver(ev('payment_intent.payment_failed', pi));
        expect(await prisma.clientPurchase.count({
          where: { stripe_payment_intent_id: pi, status: 'payment_failed' },
        })).toBe(adoptionCount + 1);
        expect(await prisma.clientPurchase.count({
          where: { stripe_payment_intent_id: pi, entitlement_active: true },
        })).toBe(0);
        stripe.status = 'succeeded';
        const result = await deliver(ev('payment_intent.succeeded', pi));
        // The unrelated provider replies now publish their own PI ids.
        // They cannot fix an already consumed success for the hosted owner.
        releaseMint.open();
        await Promise.all(creating);
        const persisted = await prisma.clientPurchase.findUniqueOrThrow({ where: { id: owner } });
        const drop = await prisma.scheduledDrop.findUniqueOrThrow({ where: { id: `drop-${owner}` } });
        expect({ result, status: persisted.status, entitled: persisted.entitlement_active,
          drop: drop.status }).toEqual({
          result: { claimed: true, purchase_id: owner, reason: 'payment_recovered' },
          status: 'paid', entitled: true, drop: 'pending',
        });
        expect(await prisma.clientPurchase.count({
          where: { stripe_payment_intent_id: pi, entitlement_active: true, id: { not: owner } },
        })).toBe(0);
      } finally {
        release.open();
        releaseMint.open();
        await Promise.all([...adopting, ...creating]);
      }
    }, 120_000,
  );
});
