-- P0 schema drift repair: create the objects prisma/schema.prisma has declared
-- since April that no migration ever created.
--
-- WHY: the production database is missing User.archived_at (and the objects
-- below). Every Prisma read of User selects every scalar column, so every User
-- read, the signup path and every cron tick fails with
-- "column User.archived_at does not exist". The same is true for UserProfile,
-- NotificationPreferences and the four tables. The fields were added to
-- schema.prisma without a migration (for example 69c80ee1, #35), and CI's
-- schema-parity diff was informational, so nothing failed.
--
-- WHAT (exactly what schema.prisma declares; DDL generated by
-- `prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma
-- --script` with Prisma 6.19.3, then wrapped in existence guards):
--   enum   ListType (grocery, shopping)
--   column User.archived_at
--   column UserProfile.bio, weight_unit, meals_per_day, water_goal_oz,
--          calorie_display, onboardingCompleted
--   column NotificationPreferences.daily_checkin_enabled,
--          weekly_summary_enabled, new_client_alerts
--   table  UserPreferences, Recipe, SavedRecipe, ListItem, with their primary
--          keys, unique constraints, indexes and foreign keys (ON DELETE
--          RESTRICT ON UPDATE CASCADE: the Prisma default for a required
--          relation with no declared onDelete).
--
-- SAFETY:
--   * Additive only. No DROP, no data rewrite, no backfill. ADD COLUMN with a
--     constant default is a catalog-only change on PostgreSQL 11+ (existing
--     rows read the default; the table is not rewritten).
--   * Idempotent: every statement is guarded (IF NOT EXISTS, catalog checks,
--     DROP POLICY IF EXISTS before CREATE POLICY), so a re-run is a no-op.
--   * Not silently wrong: a guard skips an object that already exists, so the
--     final block asserts the shape of every object (type, typmod, nullability,
--     default present, constraint actions, RLS flags) and raises if anything
--     differs, which rolls the whole file back.
--   * One transaction with bounded lock waits: lock_timeout 5 s, statement
--     timeout 30 s (SET LOCAL, so nothing leaks into later migrations). On a
--     timeout the file rolls back as a whole; recover with
--     `prisma migrate resolve --rolled-back 20270125000000_restore_schema_declared_objects`
--     and re-deploy.
--
-- RLS (the four new tables): the S1-DB-01 server-only posture used for the
-- existing per-user tables UserAIQuota and NudgeLog
-- (20261224000000_rls_close_public_exposure): ENABLE + FORCE RLS, PERMISSIVE
-- FOR ALL TO service_role, RESTRICTIVE deny-all TO anon and TO authenticated,
-- API-role privileges revoked. The tables are reached only through the backend
-- Prisma client; the mobile app issues no PostgREST (.from) calls.
--
-- ROLLBACK: forward-fix only. Every application release since April already
-- expects these objects, so rolling the app back never needs the schema rolled
-- back. down.sql exists for the CI reversibility proof; running it in
-- production would bring the outage back and delete any rows written since.

BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '30s';

-- Entry gate: the API roles the RLS section references must exist
-- (Supabase provides them; CI applies prisma/migrations/_supabase_bootstrap.sql).
DO $gate$
BEGIN
  IF (SELECT count(*) FROM pg_catalog.pg_roles
       WHERE rolname IN ('anon', 'authenticated', 'service_role')) <> 3 THEN
    RAISE EXCEPTION 'restore_schema_declared_objects: Supabase API roles (anon, authenticated, service_role) are missing';
  END IF;
END
$gate$;

-- CreateEnum
DO $enum$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_catalog.pg_type t
      JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
     WHERE t.typname = 'ListType' AND n.nspname = current_schema()
  ) THEN
    CREATE TYPE "ListType" AS ENUM ('grocery', 'shopping');
  END IF;
END
$enum$;

-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "archived_at" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "UserProfile"
  ADD COLUMN IF NOT EXISTS "bio" TEXT,
  ADD COLUMN IF NOT EXISTS "weight_unit" TEXT DEFAULT 'lbs',
  ADD COLUMN IF NOT EXISTS "meals_per_day" INTEGER,
  ADD COLUMN IF NOT EXISTS "water_goal_oz" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "calorie_display" TEXT DEFAULT 'net',
  ADD COLUMN IF NOT EXISTS "onboardingCompleted" BOOLEAN DEFAULT false;

-- AlterTable
ALTER TABLE "NotificationPreferences"
  ADD COLUMN IF NOT EXISTS "daily_checkin_enabled" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "weekly_summary_enabled" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "new_client_alerts" BOOLEAN NOT NULL DEFAULT true;

-- CreateTable
CREATE TABLE IF NOT EXISTS "UserPreferences" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "home_modules" TEXT[] DEFAULT ARRAY['hero', 'milestone', 'trustcues', 'secondary']::TEXT[],
    "notification_cadence" TEXT NOT NULL DEFAULT 'daily',
    "motivational_tone" TEXT NOT NULL DEFAULT 'direct',
    "units" TEXT NOT NULL DEFAULT 'imperial',
    "first_day_of_week" INTEGER NOT NULL DEFAULT 1,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "UserPreferences_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "Recipe" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "image_url" TEXT,
    "prep_time_min" INTEGER NOT NULL,
    "cook_time_min" INTEGER NOT NULL,
    "servings" INTEGER NOT NULL,
    "calories" DOUBLE PRECISION NOT NULL,
    "protein" DOUBLE PRECISION NOT NULL,
    "carbs" DOUBLE PRECISION NOT NULL,
    "fat" DOUBLE PRECISION NOT NULL,
    "ingredients" TEXT[],
    "instructions" TEXT[],
    "tags" TEXT[],
    "is_public" BOOLEAN NOT NULL DEFAULT true,
    "created_by_id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Recipe_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "SavedRecipe" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "recipe_id" TEXT NOT NULL,
    "saved_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SavedRecipe_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "ListItem" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "list_type" "ListType" NOT NULL,
    "name" TEXT NOT NULL,
    "quantity" DOUBLE PRECISION NOT NULL DEFAULT 1,
    "unit" TEXT,
    "is_checked" BOOLEAN NOT NULL DEFAULT false,
    "source_recipe_id" TEXT,
    "added_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ListItem_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "UserPreferences_user_id_key" ON "UserPreferences"("user_id");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "UserPreferences_user_id_idx" ON "UserPreferences"("user_id");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "Recipe_created_by_id_idx" ON "Recipe"("created_by_id");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "Recipe_is_public_idx" ON "Recipe"("is_public");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "SavedRecipe_user_id_idx" ON "SavedRecipe"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "SavedRecipe_user_id_recipe_id_key" ON "SavedRecipe"("user_id", "recipe_id");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "ListItem_user_id_list_type_idx" ON "ListItem"("user_id", "list_type");

-- AddForeignKey (guarded: ADD CONSTRAINT has no IF NOT EXISTS form)
DO $fk$
DECLARE
  fk record;
BEGIN
  FOR fk IN
    SELECT * FROM (VALUES
      ('UserPreferences', 'UserPreferences_user_id_fkey',
       'ALTER TABLE "UserPreferences" ADD CONSTRAINT "UserPreferences_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE'),
      ('Recipe', 'Recipe_created_by_id_fkey',
       'ALTER TABLE "Recipe" ADD CONSTRAINT "Recipe_created_by_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE'),
      ('SavedRecipe', 'SavedRecipe_user_id_fkey',
       'ALTER TABLE "SavedRecipe" ADD CONSTRAINT "SavedRecipe_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE'),
      ('SavedRecipe', 'SavedRecipe_recipe_id_fkey',
       'ALTER TABLE "SavedRecipe" ADD CONSTRAINT "SavedRecipe_recipe_id_fkey" FOREIGN KEY ("recipe_id") REFERENCES "Recipe"("id") ON DELETE RESTRICT ON UPDATE CASCADE'),
      ('ListItem', 'ListItem_user_id_fkey',
       'ALTER TABLE "ListItem" ADD CONSTRAINT "ListItem_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE')
    ) AS v(tbl, conname, ddl)
  LOOP
    IF NOT EXISTS (
      SELECT 1 FROM pg_catalog.pg_constraint
       WHERE conname = fk.conname
         AND conrelid = pg_catalog.to_regclass(pg_catalog.quote_ident(fk.tbl))
    ) THEN
      EXECUTE fk.ddl;
    END IF;
  END LOOP;
END
$fk$;

-- Row-level security for the four new tables (server-only posture, see header).
DO $rls$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['UserPreferences', 'Recipe', 'SavedRecipe', 'ListItem'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);

    EXECUTE format('DROP POLICY IF EXISTS %I ON %I', 'p_' || t || '_service_role_all', t);
    EXECUTE format(
      'CREATE POLICY %I ON %I AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true)',
      'p_' || t || '_service_role_all', t);
    EXECUTE format('COMMENT ON POLICY %I ON %I IS %L',
      'p_' || t || '_service_role_all', t,
      'Primitive A: service_role bypass. Table is reached only by the backend Prisma client.');

    EXECUTE format('DROP POLICY IF EXISTS %I ON %I', 'deny_all_anon_' || t, t);
    EXECUTE format(
      'CREATE POLICY %I ON %I AS RESTRICTIVE FOR ALL TO anon USING (false) WITH CHECK (false)',
      'deny_all_anon_' || t, t);
    EXECUTE format('COMMENT ON POLICY %I ON %I IS %L',
      'deny_all_anon_' || t, t,
      'RESTRICTIVE deny-all: anon can never read or write this server-only table.');

    EXECUTE format('DROP POLICY IF EXISTS %I ON %I', 'deny_all_authenticated_' || t, t);
    EXECUTE format(
      'CREATE POLICY %I ON %I AS RESTRICTIVE FOR ALL TO authenticated USING (false) WITH CHECK (false)',
      'deny_all_authenticated_' || t, t);
    EXECUTE format('COMMENT ON POLICY %I ON %I IS %L',
      'deny_all_authenticated_' || t, t,
      'RESTRICTIVE deny-all: authenticated principals can never read or write this server-only table.');

    EXECUTE format('REVOKE ALL PRIVILEGES ON TABLE %I FROM PUBLIC, anon, authenticated', t);
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE %I TO service_role', t);
  END LOOP;
END
$rls$;

-- Post-condition: every object this file is responsible for exists with the
-- declared column type/typmod, nullability and default presence, FK target table
-- and ON DELETE/ON UPDATE actions, index uniqueness, RLS flags, policies and
-- per-role grants. It does NOT compare default expressions, PK/FK column lists or
-- index key columns/predicates. That is sufficient for this inventory: every
-- object was absent in production (read-only catalog check, 2026-10-01) and is
-- created above by Prisma's own DDL. A pre-existing object with the right name but
-- a different default expression or key column list would not be caught here.
DO $verify$
DECLARE
  r record;
  bad text[] := ARRAY[]::text[];
BEGIN
  -- Columns: (table, column, pg_type.typname, NOT NULL, has default, typmod).
  FOR r IN
    SELECT e.tbl, e.col, e.typ, e.nonnull, e.hasdef, e.typmod,
           ty.typname::text AS a_typ, a.attnotnull AS a_notnull,
           a.atthasdef AS a_hasdef, a.atttypmod AS a_typmod
      FROM (VALUES
        ('User', 'archived_at', 'timestamp', false, false, 3),
        ('UserProfile', 'bio', 'text', false, false, -1),
        ('UserProfile', 'weight_unit', 'text', false, true, -1),
        ('UserProfile', 'meals_per_day', 'int4', false, false, -1),
        ('UserProfile', 'water_goal_oz', 'float8', false, false, -1),
        ('UserProfile', 'calorie_display', 'text', false, true, -1),
        ('UserProfile', 'onboardingCompleted', 'bool', false, true, -1),
        ('NotificationPreferences', 'daily_checkin_enabled', 'bool', true, true, -1),
        ('NotificationPreferences', 'weekly_summary_enabled', 'bool', true, true, -1),
        ('NotificationPreferences', 'new_client_alerts', 'bool', true, true, -1),
        ('UserPreferences', 'id', 'text', true, false, -1),
        ('UserPreferences', 'user_id', 'text', true, false, -1),
        ('UserPreferences', 'home_modules', '_text', false, true, -1),
        ('UserPreferences', 'notification_cadence', 'text', true, true, -1),
        ('UserPreferences', 'motivational_tone', 'text', true, true, -1),
        ('UserPreferences', 'units', 'text', true, true, -1),
        ('UserPreferences', 'first_day_of_week', 'int4', true, true, -1),
        ('UserPreferences', 'updated_at', 'timestamp', true, false, 3),
        ('Recipe', 'id', 'text', true, false, -1),
        ('Recipe', 'title', 'text', true, false, -1),
        ('Recipe', 'description', 'text', false, false, -1),
        ('Recipe', 'image_url', 'text', false, false, -1),
        ('Recipe', 'prep_time_min', 'int4', true, false, -1),
        ('Recipe', 'cook_time_min', 'int4', true, false, -1),
        ('Recipe', 'servings', 'int4', true, false, -1),
        ('Recipe', 'calories', 'float8', true, false, -1),
        ('Recipe', 'protein', 'float8', true, false, -1),
        ('Recipe', 'carbs', 'float8', true, false, -1),
        ('Recipe', 'fat', 'float8', true, false, -1),
        ('Recipe', 'ingredients', '_text', false, false, -1),
        ('Recipe', 'instructions', '_text', false, false, -1),
        ('Recipe', 'tags', '_text', false, false, -1),
        ('Recipe', 'is_public', 'bool', true, true, -1),
        ('Recipe', 'created_by_id', 'text', true, false, -1),
        ('Recipe', 'created_at', 'timestamp', true, true, 3),
        ('Recipe', 'updated_at', 'timestamp', true, false, 3),
        ('SavedRecipe', 'id', 'text', true, false, -1),
        ('SavedRecipe', 'user_id', 'text', true, false, -1),
        ('SavedRecipe', 'recipe_id', 'text', true, false, -1),
        ('SavedRecipe', 'saved_at', 'timestamp', true, true, 3),
        ('ListItem', 'id', 'text', true, false, -1),
        ('ListItem', 'user_id', 'text', true, false, -1),
        ('ListItem', 'list_type', 'ListType', true, false, -1),
        ('ListItem', 'name', 'text', true, false, -1),
        ('ListItem', 'quantity', 'float8', true, true, -1),
        ('ListItem', 'unit', 'text', false, false, -1),
        ('ListItem', 'is_checked', 'bool', true, true, -1),
        ('ListItem', 'source_recipe_id', 'text', false, false, -1),
        ('ListItem', 'added_at', 'timestamp', true, true, 3)
      ) AS e(tbl, col, typ, nonnull, hasdef, typmod)
      LEFT JOIN pg_catalog.pg_attribute a
        ON a.attrelid = pg_catalog.to_regclass(pg_catalog.quote_ident(e.tbl))
       AND a.attname = e.col AND a.attnum > 0 AND NOT a.attisdropped
      LEFT JOIN pg_catalog.pg_type ty ON ty.oid = a.atttypid
  LOOP
    IF r.a_typ IS DISTINCT FROM r.typ
       OR r.a_notnull IS DISTINCT FROM r.nonnull
       OR r.a_hasdef IS DISTINCT FROM r.hasdef
       OR r.a_typmod IS DISTINCT FROM r.typmod THEN
      bad := array_append(bad, format('column %s.%s', r.tbl, r.col));
    END IF;
  END LOOP;

  -- The four new tables carry no columns beyond the declared ones.
  FOR r IN
    SELECT e.tbl, e.n,
           (SELECT count(*) FROM pg_catalog.pg_attribute a
             WHERE a.attrelid = pg_catalog.to_regclass(pg_catalog.quote_ident(e.tbl))
               AND a.attnum > 0 AND NOT a.attisdropped) AS actual
      FROM (VALUES ('UserPreferences', 8), ('Recipe', 18), ('SavedRecipe', 4), ('ListItem', 9))
        AS e(tbl, n)
  LOOP
    IF r.actual <> r.n THEN
      bad := array_append(bad, format('table %s has %s columns, expected %s', r.tbl, r.actual, r.n));
    END IF;
  END LOOP;

  -- Enum labels, in declared order.
  IF (SELECT array_agg(en.enumlabel::text ORDER BY en.enumsortorder)
        FROM pg_catalog.pg_enum en
        JOIN pg_catalog.pg_type ty ON ty.oid = en.enumtypid
        JOIN pg_catalog.pg_namespace n ON n.oid = ty.typnamespace
       WHERE ty.typname = 'ListType' AND n.nspname = current_schema())
     IS DISTINCT FROM ARRAY['grocery', 'shopping'] THEN
    bad := array_append(bad, 'enum ListType labels'::text);
  END IF;

  -- Primary keys and foreign keys (referenced table, ON DELETE r = RESTRICT,
  -- ON UPDATE c = CASCADE).
  FOR r IN
    SELECT e.tbl, e.conname, e.contype, e.reftbl,
           c.contype AS a_contype, c.confdeltype AS a_del, c.confupdtype AS a_upd,
           c.confrelid AS a_ref
      FROM (VALUES
        ('UserPreferences', 'UserPreferences_pkey', 'p', NULL),
        ('Recipe', 'Recipe_pkey', 'p', NULL),
        ('SavedRecipe', 'SavedRecipe_pkey', 'p', NULL),
        ('ListItem', 'ListItem_pkey', 'p', NULL),
        ('UserPreferences', 'UserPreferences_user_id_fkey', 'f', 'User'),
        ('Recipe', 'Recipe_created_by_id_fkey', 'f', 'User'),
        ('SavedRecipe', 'SavedRecipe_user_id_fkey', 'f', 'User'),
        ('SavedRecipe', 'SavedRecipe_recipe_id_fkey', 'f', 'Recipe'),
        ('ListItem', 'ListItem_user_id_fkey', 'f', 'User')
      ) AS e(tbl, conname, contype, reftbl)
      LEFT JOIN pg_catalog.pg_constraint c
        ON c.conname = e.conname
       AND c.conrelid = pg_catalog.to_regclass(pg_catalog.quote_ident(e.tbl))
  LOOP
    IF r.a_contype IS DISTINCT FROM r.contype::"char" THEN
      bad := array_append(bad, format('constraint %s', r.conname));
    ELSIF r.contype = 'f' AND (
          r.a_del IS DISTINCT FROM 'r'::"char"
       OR r.a_upd IS DISTINCT FROM 'c'::"char"
       OR r.a_ref IS DISTINCT FROM pg_catalog.to_regclass(pg_catalog.quote_ident(r.reftbl))) THEN
      bad := array_append(bad, format('foreign key %s actions/target', r.conname));
    END IF;
  END LOOP;

  -- Indexes (name, unique).
  FOR r IN
    SELECT e.idx, e.uniq, i.indisunique AS a_uniq
      FROM (VALUES
        ('UserPreferences_user_id_key', true),
        ('UserPreferences_user_id_idx', false),
        ('Recipe_created_by_id_idx', false),
        ('Recipe_is_public_idx', false),
        ('SavedRecipe_user_id_idx', false),
        ('SavedRecipe_user_id_recipe_id_key', true),
        ('ListItem_user_id_list_type_idx', false)
      ) AS e(idx, uniq)
      LEFT JOIN pg_catalog.pg_index i
        ON i.indexrelid = pg_catalog.to_regclass(pg_catalog.quote_ident(e.idx))
  LOOP
    IF r.a_uniq IS DISTINCT FROM r.uniq THEN
      bad := array_append(bad, format('index %s', r.idx));
    END IF;
  END LOOP;

  -- RLS enabled and forced on the four new tables.
  FOR r IN
    SELECT t AS tbl, c.relrowsecurity, c.relforcerowsecurity
      FROM unnest(ARRAY['UserPreferences', 'Recipe', 'SavedRecipe', 'ListItem']) AS t
      LEFT JOIN pg_catalog.pg_class c
        ON c.oid = pg_catalog.to_regclass(pg_catalog.quote_ident(t))
  LOOP
    IF r.relrowsecurity IS DISTINCT FROM true OR r.relforcerowsecurity IS DISTINCT FROM true THEN
      bad := array_append(bad, format('row level security on %s', r.tbl));
    END IF;
  END LOOP;

  -- Policies: exactly the three server-only policies on each new table.
  FOR r IN
    SELECT t AS tbl,
           (SELECT count(*) FROM pg_catalog.pg_policy p WHERE p.polrelid = c.oid) AS n_all,
           (SELECT count(*) FROM pg_catalog.pg_policy p
             WHERE p.polrelid = c.oid AND p.polname = 'p_' || t || '_service_role_all'
               AND p.polpermissive AND p.polcmd = '*'
               AND p.polroles = ARRAY['service_role'::regrole::oid]
               AND pg_catalog.pg_get_expr(p.polqual, p.polrelid) = 'true'
               AND pg_catalog.pg_get_expr(p.polwithcheck, p.polrelid) = 'true') AS n_service,
           (SELECT count(*) FROM pg_catalog.pg_policy p
             WHERE p.polrelid = c.oid AND p.polname IN ('deny_all_anon_' || t, 'deny_all_authenticated_' || t)
               AND NOT p.polpermissive AND p.polcmd = '*'
               AND p.polroles = ARRAY[(CASE WHEN p.polname = 'deny_all_anon_' || t
                                            THEN 'anon' ELSE 'authenticated' END)::regrole::oid]
               AND pg_catalog.pg_get_expr(p.polqual, p.polrelid) = 'false'
               AND pg_catalog.pg_get_expr(p.polwithcheck, p.polrelid) = 'false') AS n_deny
      FROM unnest(ARRAY['UserPreferences', 'Recipe', 'SavedRecipe', 'ListItem']) AS t
      LEFT JOIN pg_catalog.pg_class c
        ON c.oid = pg_catalog.to_regclass(pg_catalog.quote_ident(t))
  LOOP
    IF r.n_all <> 3 OR r.n_service <> 1 OR r.n_deny <> 2 THEN
      bad := array_append(bad, format('policies on %s (total %s, service_role %s, deny %s)',
                                      r.tbl, r.n_all, r.n_service, r.n_deny));
    END IF;
  END LOOP;

  -- Table privileges: none for PUBLIC/anon/authenticated, DML for service_role.
  FOR r IN
    SELECT t AS tbl, g.rol, g.priv, g.want,
           pg_catalog.has_table_privilege(g.rol, pg_catalog.to_regclass(pg_catalog.quote_ident(t)), g.priv) AS got
      FROM unnest(ARRAY['UserPreferences', 'Recipe', 'SavedRecipe', 'ListItem']) AS t
      CROSS JOIN (VALUES
        ('public', 'SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER', false),
        ('anon', 'SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER', false),
        ('authenticated', 'SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER', false),
        ('service_role', 'SELECT', true),
        ('service_role', 'INSERT', true),
        ('service_role', 'UPDATE', true),
        ('service_role', 'DELETE', true)
      ) AS g(rol, priv, want)
  LOOP
    IF r.got IS DISTINCT FROM r.want THEN
      bad := array_append(bad, format('privilege %s for %s on %s is %s', r.priv, r.rol, r.tbl, r.got));
    END IF;
  END LOOP;

  IF cardinality(bad) > 0 THEN
    RAISE EXCEPTION 'restore_schema_declared_objects: objects missing or not in the declared shape: %',
      array_to_string(bad, '; ');
  END IF;
END
$verify$;

COMMIT;
