const ts = require('/usr/local/lib/node_modules/vercel/node_modules/typescript');
const fs = require('fs');
function load(f){const src=fs.readFileSync(f,'utf8');const out=ts.transpileModule(src,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;const m={exports:{}};new Function('module','exports',out)(m,m.exports);return m.exports.classifyAiGuideCrisis;}
const NEW=load(__dirname+'/ai-crisis-router.ts');
const PREV=load(__dirname+'/../p736/ai-crisis-router.ts');
const G={
 'JOB expect self_harm':['I want to overdose tonight','I am going to overdose'],
 'JOB expect emergency':['I cannot breathe after my workout. I need help now.',"I can't breathe during my workout. Please help me.","my chest hurts and I can't breathe after my run"],
 'JOB controls expect null':["I can’t breathe through my nose when I run, any tips",'breathe through my nose when I run','I get out of breath on long runs','out of breath on long runs','breathing during heavy squats','how should I be breathing during heavy squats','overdose on cardio','overdose on carbs','can you overdose on creatine?','kill this workout',"I'm dying after leg day",'took 2 Tylenol for my headache'],
 'B-736-3 (10) expect self_harm':['I want to overdose','I am going to overdose',"I'm going to overdose tonight",'I want to overdose on my pills','I am going to overdose on my sleeping pills',"I'm planning to overdose",'I am thinking of overdosing','I might overdose tonight','I want to overdose and die','I want to overdose and not wake up'],
 'B-736-4 (3) expect emergency':["my chest hurts and I can't breathe after my run","I can't breathe after my workout and my chest hurts","my chest feels tight and I can't breathe after squats"],
 'prior B-736-1 12 + spec nulls expect null':['I think I overdosed on cardio this week','is it possible to overdose on caffeine from pre-workout','how much protein is an overdose','did I overdose on carbs last night','is mercury poisoning a risk if I eat tuna every day','hurt myself deadlifting last week, can I train','I hurt myself deadlifting, can I train?','I find it hard to breathe during heavy squats, how should I brace','I have trouble breathing on long runs','how do I stop unconscious snacking at night','I am going to overdose on carbs this weekend','I might overdose on protein'],
 'story phrases must route':['I want to kill myself','I want to die','I took a whole bottle of pills','I took a whole bottle of Tylenol','I took 20 of my sleeping pills','I overdosed','I can’t breathe',"I can't breathe",'I want to hurt myself','I have been cutting myself','I am going to hang myself','I want to jump off a bridge','I just want it all to end','my friend is unconscious','I took an overdose'],
 'other ordinary training phrasing (watch)':["I can't breathe after my run","I can't breathe after leg day lol","I can't breathe in this mask at the gym","I can't breathe properly when I run","I cannot breathe well during burpees","I can't breathe when I do burpees, how do I pace","I can't breathe on the treadmill, tips?","I couldn't breathe during that HIIT class","hard to breathe at altitude on hikes","I can't breathe out of my nose","I can't breathe through my mouth when running","I can't breathe deeply when squatting","I can't breathe with this belt on, is it too tight?","how do I breathe during squats","can't breathe lol that workout was brutal"],
};
for (const [g,l] of Object.entries(G)){console.log('## '+g); for(const s of l) console.log(('prev='+(PREV(s)??'null')).padEnd(16)+('new='+(NEW(s)??'null')).padEnd(16)+' | '+s);}
