/**
 * DNS verification for custom landing-page domains — R49 Phase 4.
 *
 * Two records must be present before a domain is considered `verified`:
 *
 *   1. TXT on `_tgp-verify.<domain>` containing `tgp-verify=<token>`.
 *      Proves the coach controls the zone (the token was generated by
 *      the platform at row creation and is not derivable from the
 *      domain name alone).
 *
 *   2. CNAME on `<domain>` resolving to `custom.joingrowthproject.com`
 *      OR an A record matching the Fly anycast IP set
 *      (FLY_ANYCAST_IPS env var, comma-separated; default to the
 *      published Fly anycast pair so the dev / staging boot path
 *      works without explicit config).
 *
 * The service exposes a single `verify(domain, token)` method that
 * returns `{ verified, reason? }`.  Pure side-effect-free wrapper
 * around `dns/promises` so unit tests can mock the resolver module
 * with `jest.mock('dns/promises', ...)`.
 *
 * Why we don't use a single CNAME on the apex: apex CNAMEs are
 * forbidden by RFC 1034 §3.6.2.  Coaches who want to point a bare
 * domain (`example.com`, not `coaching.example.com`) need ALIAS /
 * ANAME support from their DNS provider OR they must use an A record
 * — both paths are accepted here.
 */

import { Injectable, Logger } from '@nestjs/common';
import { promises as dns } from 'dns';

export interface DnsVerifyResult {
  verified: boolean;
  /** Short tag suitable for `coach_landing_page_domain.last_error`. */
  reason?: string;
}

const DEFAULT_CNAME_TARGET = 'custom.joingrowthproject.com';
// Fly.io anycast IP pair published at https://fly.io/docs/networking/services/
// — `66.241.124.0` and `66.241.125.0` are the v4 anycast addresses.  Coaches
// who can only set A records (no CNAME, no ALIAS) must point at one of these.
const DEFAULT_FLY_ANYCAST = ['66.241.124.0', '66.241.125.0'];

@Injectable()
export class DomainDnsService {
  private readonly logger = new Logger(DomainDnsService.name);

  /** Override target — accessor so env changes are picked up at request time. */
  cnameTarget(): string {
    return (
      process.env.CUSTOM_DOMAIN_CNAME_TARGET?.trim().toLowerCase() ||
      DEFAULT_CNAME_TARGET
    );
  }

  flyAnycastIps(): string[] {
    const raw = process.env.FLY_ANYCAST_IPS?.trim();
    if (!raw) return DEFAULT_FLY_ANYCAST;
    return raw
      .split(',')
      .map((s) => s.trim())
      .filter((s) => s.length > 0);
  }

  /**
   * Verify both TXT and CNAME/A records for a domain.  Either record
   * being absent / wrong shape returns `verified=false` with a short
   * `reason` tag (see DnsVerifyResult for what callers persist).
   *
   * The DNS lookups run sequentially: TXT first, because if the coach
   * has not put the token in DNS yet there's no reason to fan-out a
   * second query.  Latency budget per call is bounded by the platform
   * resolver's default timeout (5s under Node 20); the worker that
   * calls us has its own retry / backoff so we do not need an
   * explicit timeout here.
   */
  async verify(domain: string, token: string): Promise<DnsVerifyResult> {
    const normalized = domain.trim().toLowerCase();
    if (!normalized) {
      return { verified: false, reason: 'invalid_domain' };
    }

    const txtResult = await this.checkTxt(normalized, token);
    if (!txtResult.verified) return txtResult;

    const cnameResult = await this.checkCnameOrA(normalized);
    if (!cnameResult.verified) return cnameResult;

    return { verified: true };
  }

  /**
   * Exposed separately so the coach UX endpoint can poll without
   * re-running the CNAME branch when only the TXT step is needed.
   */
  async checkTxt(domain: string, token: string): Promise<DnsVerifyResult> {
    const host = `_tgp-verify.${domain}`;
    const expected = `tgp-verify=${token}`;
    let records: string[][];
    try {
      records = await dns.resolveTxt(host);
    } catch (err) {
      const code = (err as NodeJS.ErrnoException).code;
      if (code === 'ENOTFOUND' || code === 'ENODATA') {
        return { verified: false, reason: 'txt_missing' };
      }
      this.logger.warn(`TXT lookup for ${host} threw ${code}`);
      return { verified: false, reason: `txt_dns_error:${code ?? 'unknown'}` };
    }
    const flat = records.map((parts) => parts.join('').trim());
    const hit = flat.some((v) => v === expected);
    if (!hit) {
      return { verified: false, reason: 'txt_mismatch' };
    }
    return { verified: true };
  }

  /**
   * Accept either a CNAME pointing at the configured target OR an
   * A record matching one of the Fly anycast IPs.  Coaches whose
   * registrars do not support CNAME flattening (e.g. apex domains)
   * still get a working path via the A-record fallback.
   */
  async checkCnameOrA(domain: string): Promise<DnsVerifyResult> {
    const target = this.cnameTarget();
    try {
      const cnames = await dns.resolveCname(domain);
      const hit = cnames.some(
        (c) => c.toLowerCase().replace(/\.$/, '') === target,
      );
      if (hit) return { verified: true };
      // CNAME exists but points somewhere else — surface mismatch.
      if (cnames.length > 0) {
        return { verified: false, reason: 'cname_mismatch' };
      }
    } catch (err) {
      const code = (err as NodeJS.ErrnoException).code;
      // ENOTFOUND / ENODATA — fall through to A-record check.
      if (code !== 'ENOTFOUND' && code !== 'ENODATA') {
        this.logger.warn(`CNAME lookup for ${domain} threw ${code}`);
        return { verified: false, reason: `cname_dns_error:${code ?? 'unknown'}` };
      }
    }
    // No CNAME (or CNAME lookup hit ENOTFOUND) — try A records.
    try {
      const ips = await dns.resolve4(domain);
      const acceptable = new Set(this.flyAnycastIps());
      const hit = ips.some((ip) => acceptable.has(ip));
      if (hit) return { verified: true };
      if (ips.length > 0) {
        return { verified: false, reason: 'a_record_mismatch' };
      }
    } catch (err) {
      const code = (err as NodeJS.ErrnoException).code;
      if (code === 'ENOTFOUND' || code === 'ENODATA') {
        return { verified: false, reason: 'cname_missing' };
      }
      this.logger.warn(`A lookup for ${domain} threw ${code}`);
      return { verified: false, reason: `a_dns_error:${code ?? 'unknown'}` };
    }
    return { verified: false, reason: 'cname_missing' };
  }
}
