-- Schema parity baseline: drift between the database the migration chain builds and
-- prisma/schema.prisma that predates the blocking gate (BL-MIGRATION-REBASELINE).
-- Read by scripts/ci/schema-parity-gate.js in .github/workflows/schema-parity.yml.
-- One normalized item per line. This file may only shrink: when a change fixes an item,
-- delete its line in the same change. Never add a line to accept new drift; write the
-- migration (or the schema change) that removes it. Tables, enums, enum values and
-- columns missing from the chain can never be listed here; the gate rejects them.

ALTER INDEX "BuildWeekDayCompletion_enrollment_day_key" RENAME TO "BuildWeekDayCompletion_enrollment_id_day_number_key";
ALTER INDEX "ClientCoachConsent_client_coach_scope_key" RENAME TO "ClientCoachConsent_client_id_coach_id_scope_key";
ALTER INDEX "CoachAvailabilityOverride_coach_date_start_kind_key" RENAME TO "CoachAvailabilityOverride_coach_id_date_start_minute_kind_key";
ALTER INDEX "CoachBrief_coach_date_key" RENAME TO "CoachBrief_coach_id_brief_date_key";
ALTER INDEX "CoachDailyLog_coach_log_date_key" RENAME TO "CoachDailyLog_coach_id_log_date_key";
ALTER INDEX "MessageReport_reporter_message_key" RENAME TO "MessageReport_reporter_id_message_id_key";
ALTER INDEX "NotificationDigestLog_user_digest_window_key" RENAME TO "NotificationDigestLog_user_id_digest_kind_window_date_key";
ALTER INDEX "NotificationDigestLog_user_id_digest_kind_idx" RENAME TO "NotificationDigestLog_user_id_digest_kind_window_date_idx";
ALTER INDEX "PaymentReminder_purchase_kind_channel_window_idx" RENAME TO "PaymentReminder_purchase_id_kind_channel_window_key_key";
ALTER INDEX "ScoutReconstructedEntity_coach_id_source_platform_entity_type_s" RENAME TO "ScoutReconstructedEntity_coach_id_source_platform_entity_ty_key";
ALTER INDEX "SplitLedgerEntry_purchase_kind_payee_idx" RENAME TO "SplitLedgerEntry_purchase_id_kind_payee_user_id_key";
ALTER INDEX "SubCoachMutationIdempotency_actor_key" RENAME TO "SubCoachMutationIdempotency_actor_id_idempotency_key_key";
ALTER INDEX "UserBlock_pair_key" RENAME TO "UserBlock_blocker_id_blocked_id_key";
ALTER INDEX "WorkoutBuilderIdempotencyKey_user_route_key_key" RENAME TO "WorkoutBuilderIdempotencyKey_user_id_route_key_idempotency__key";
ALTER INDEX "community_classroom_posts_workspace_id_cohort_id_pinned_pinn_id" RENAME TO "community_classroom_posts_workspace_id_cohort_id_pinned_pin_idx";
ALTER INDEX "community_classroom_posts_workspace_id_cohort_id_status_rele_id" RENAME TO "community_classroom_posts_workspace_id_cohort_id_status_rel_idx";
ALTER INDEX "community_responses_target_type_target_id_user_id_response_kind" RENAME TO "community_responses_target_type_target_id_user_id_response__key";
ALTER INDEX "community_search_entries_workspaceId_cohortId_kind_createdAt_id" RENAME TO "community_search_entries_workspaceId_cohortId_kind_createdA_idx";
ALTER INDEX "community_voice_notes_workspace_id_conversation_id_created_a_id" RENAME TO "community_voice_notes_workspace_id_conversation_id_created__idx";
ALTER TABLE "Applicant" DROP CONSTRAINT "Applicant_user_id_fkey";
ALTER TABLE "Application" DROP CONSTRAINT "Application_applicant_id_fkey";
ALTER TABLE "Application" DROP CONSTRAINT "Application_applicant_user_id_fkey";
ALTER TABLE "Application" DROP CONSTRAINT "Application_hirer_id_fkey";
ALTER TABLE "Application" DROP CONSTRAINT "Application_listing_id_fkey";
ALTER TABLE "BloodworkAttachment" ALTER COLUMN "updated_at" DROP DEFAULT;
ALTER TABLE "BloodworkPanel" ALTER COLUMN "updated_at" DROP DEFAULT;
ALTER TABLE "BloodworkResult" ALTER COLUMN "updated_at" DROP DEFAULT;
ALTER TABLE "CheckIn" DROP CONSTRAINT "CheckIn_coach_id_fkey";
ALTER TABLE "CoachBrief" ALTER COLUMN "updated_at" DROP DEFAULT;
ALTER TABLE "CoachBriefPreferences" ALTER COLUMN "updated_at" DROP DEFAULT;
ALTER TABLE "CoachBriefPushLedger" ALTER COLUMN "updated_at" DROP DEFAULT;
ALTER TABLE "CoachCreditPackPurchase" ADD CONSTRAINT "CoachCreditPackPurchase_budget_id_fkey" FOREIGN KEY ("budget_id") REFERENCES "CoachAIBudget"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CoachCreditPackPurchase" ADD CONSTRAINT "CoachCreditPackPurchase_coach_user_id_fkey" FOREIGN KEY ("coach_user_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CoachCreditPackPurchase" DROP CONSTRAINT "CoachCreditPackPurchase_budget_id_fkey";
ALTER TABLE "CoachCreditPackPurchase" DROP CONSTRAINT "CoachCreditPackPurchase_coach_user_id_fkey";
ALTER TABLE "CoachCrmIntegration" ALTER COLUMN "field_mapping" DROP DEFAULT;
ALTER TABLE "CoachDailyLog" ALTER COLUMN "updated_at" DROP DEFAULT;
ALTER TABLE "CoachLandingLead" ALTER COLUMN "next_eligible_at" SET DATA TYPE TIMESTAMP(3);
ALTER TABLE "CoachLandingLead" ALTER COLUMN "payload" DROP DEFAULT;
ALTER TABLE "CoachLandingLead" ALTER COLUMN "synced_to" DROP DEFAULT;
ALTER TABLE "CoachLandingPage" ALTER COLUMN "lead_capture_fields" DROP DEFAULT;
ALTER TABLE "CoachLandingPage" ALTER COLUMN "package_ids" DROP DEFAULT;
ALTER TABLE "CoachLandingPage" ALTER COLUMN "updated_at" DROP DEFAULT;
ALTER TABLE "CoachLandingPageSection" ALTER COLUMN "payload" DROP DEFAULT;
ALTER TABLE "CoachOffer" DROP CONSTRAINT "CoachOffer_applicant_user_id_fkey";
ALTER TABLE "CoachOffer" DROP CONSTRAINT "CoachOffer_head_coach_id_fkey";
ALTER TABLE "CoachProfile" ADD CONSTRAINT "CoachProfile_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CoachProfile" ALTER COLUMN "updated_at" DROP DEFAULT;
ALTER TABLE "CoachProfile" DROP CONSTRAINT "CoachProfile_user_id_fkey";
ALTER TABLE "CommunityWin" ADD CONSTRAINT "CommunityWin_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CommunityWin" DROP CONSTRAINT "CommunityWin_user_id_fkey";
ALTER TABLE "DataExportRequest" DROP CONSTRAINT "DataExportRequest_user_id_fkey";
ALTER TABLE "InviteCode" ADD CONSTRAINT "InviteCode_coach_id_fkey" FOREIGN KEY ("coach_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "InviteCode" DROP CONSTRAINT "InviteCode_coach_id_fkey";
ALTER TABLE "JobListing" DROP CONSTRAINT "JobListing_hirer_id_fkey";
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Notification" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "Notification" DROP CONSTRAINT "Notification_user_id_fkey";
ALTER TABLE "NotificationDigestLog" ADD CONSTRAINT "NotificationDigestLog_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "NotificationDigestLog" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "NotificationDigestLog" DROP CONSTRAINT "NotificationDigestLog_user_id_fkey";
ALTER TABLE "UserProfile" ALTER COLUMN "dietary_restrictions" DROP DEFAULT;
ALTER TABLE "UserProfile" ALTER COLUMN "equipment_access" DROP DEFAULT;
ALTER TABLE "WorkoutBuilderIdempotencyKey" ALTER COLUMN "status" SET DATA TYPE TEXT;
ALTER TABLE "WorkoutBuilderIdempotencyKey" ALTER COLUMN "updated_at" DROP DEFAULT;
ALTER TABLE "community_messages" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "community_messages" DROP CONSTRAINT "community_messages_cohort_id_fkey";
ALTER TABLE "community_messages" DROP CONSTRAINT "community_messages_workspace_id_fkey";
ALTER TABLE "community_search_entries" DROP COLUMN "search_tsv";
ALTER TABLE "community_search_entries" DROP CONSTRAINT "community_search_entries_cohortId_fkey";
ALTER TABLE "community_search_entries" DROP CONSTRAINT "community_search_entries_workspaceId_fkey";
ALTER TABLE "community_wearable_prompt_sources" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "community_wearable_prompt_sources" DROP CONSTRAINT "community_wearable_prompt_sources_sampleId_fkey";
ALTER TABLE "community_wearable_prompts" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "community_wearable_prompts" DROP CONSTRAINT "community_wearable_prompts_clientId_fkey";
ALTER TABLE "community_wearable_prompts" DROP CONSTRAINT "community_wearable_prompts_coachId_fkey";
ALTER TABLE "community_wearable_prompts" DROP CONSTRAINT "community_wearable_prompts_workspaceId_fkey";
ALTER TABLE "recent_auth_nonce" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3);
ALTER TABLE "recent_auth_nonce" ALTER COLUMN "expires_at" SET DATA TYPE TIMESTAMP(3);
CREATE INDEX "ChurnIntervention_client_id_created_at_idx" ON "ChurnIntervention"("client_id", "created_at");
CREATE INDEX "ChurnIntervention_coach_id_status_created_at_idx" ON "ChurnIntervention"("coach_id", "status", "created_at");
CREATE INDEX "CoachLandingLead_coach_id_created_at_idx" ON "CoachLandingLead"("coach_id", "created_at");
CREATE INDEX "CoachLandingLead_page_id_created_at_idx" ON "CoachLandingLead"("page_id", "created_at");
CREATE INDEX "CoachLandingPageView_page_id_created_at_idx" ON "CoachLandingPageView"("page_id", "created_at");
CREATE INDEX "NotificationDigestLog_status_created_at_idx" ON "NotificationDigestLog"("status", "created_at");
CREATE INDEX "Notification_kind_created_at_idx" ON "Notification"("kind", "created_at");
CREATE INDEX "Notification_user_id_created_at_idx" ON "Notification"("user_id", "created_at");
CREATE UNIQUE INDEX "CoachPackage_share_token_key" ON "CoachPackage"("share_token");
CREATE UNIQUE INDEX "ScoutImport_import_intent_id_key" ON "ScoutImport"("import_intent_id");
CREATE UNIQUE INDEX "SubCoachInvite_token_hash_key" ON "SubCoachInvite"("token_hash");
DROP INDEX "ChurnIntervention_client_id_created_at_idx";
DROP INDEX "ChurnIntervention_coach_id_status_created_at_idx";
DROP INDEX "CoachLandingLead_coach_id_created_at_idx";
DROP INDEX "CoachLandingLead_page_id_created_at_idx";
DROP INDEX "CoachLandingPageView_page_id_created_at_idx";
DROP INDEX "NotificationDigestLog_status_idx";
DROP INDEX "Notification_kind_created_at_idx";
DROP INDEX "Notification_user_id_created_at_idx";
DROP INDEX "User_first_win_completed_at_idx";
DROP INDEX "WorkoutBuilderIdempotencyKey_status_created_at_idx";
DROP INDEX "community_search_entries_search_tsv_gin";
DROP TABLE "DataExportRequest";
DROP TABLE "deletion_audit";
