-- Roman v1.1 memory (R11-M1, A-ROMAN11-124 plan): Roman's notes about a
-- client, rolling day/week/month summaries, and per-client job state.
--
-- Additive only: three new tables, their indexes, FKs, CHECK constraints and
-- RLS. No existing table, column, index or constraint is altered or dropped.
-- The User / RomanMessage back-relations in schema.prisma are Prisma-virtual
-- and emit no DDL. Nothing writes these tables until a later slice ships the
-- writers behind FEATURE_ROMAN_MEMORY (default off). Reverse: down.sql.
--
-- RLS POLICY CITATION (ENGINEERING_RULES §2). Server-only tables: the backend
-- (service_role) reads and writes them; nobody else does. Coaches never see a
-- client's memory, and the client sees it only through a server projection.
--   p_romanclientnote_service_role_all      service_role ALL
--   p_romanclientsummary_service_role_all   service_role ALL
--   p_romanmemorystate_service_role_all     service_role ALL
--   p_<table>_anon_deny                     RESTRICTIVE anon deny-all
--   no client, coach, sub-coach or owner SELECT policy; no public write policy
--   REVOKE ALL FROM anon, authenticated (no PostgREST table grant)
--
-- Chat deletion: RomanService.eraseSessionInTx hard-deletes a chat's
-- messages. RomanClientNote.source_message_id is ON DELETE SET NULL, so the
-- note stays with a null source (plan decision 9: notes survive chat
-- deletion; account deletion removes them).
-- Account erasure: the account-deletion manifest deletes all three tables by
-- client_id (the User row is tombstoned, so the CASCADE FKs never fire).

SET lock_timeout = '5s';

-- =====================================================================
-- 1) Tables (DDL as generated by prisma migrate diff)
-- =====================================================================
CREATE TABLE "RomanClientNote" (
    "id" TEXT NOT NULL,
    "client_id" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "text" TEXT NOT NULL,
    "source_kind" TEXT NOT NULL DEFAULT 'roman_chat',
    "source_message_id" TEXT,
    "source_at" TIMESTAMP(3) NOT NULL,
    "expires_at" TIMESTAMP(3),
    "superseded_at" TIMESTAMP(3),
    "superseded_by_id" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RomanClientNote_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "RomanClientSummary" (
    "id" TEXT NOT NULL,
    "client_id" TEXT NOT NULL,
    "period" TEXT NOT NULL,
    "period_start" DATE NOT NULL,
    "text" TEXT NOT NULL,
    "facts" JSONB NOT NULL,
    "input_hash" TEXT NOT NULL,
    "model_id" TEXT NOT NULL,
    "generated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RomanClientSummary_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "RomanMemoryState" (
    "client_id" TEXT NOT NULL,
    "notes_watermark_at" TIMESTAMP(3),
    "summaries_through" DATE,
    "last_run_at" TIMESTAMP(3),
    "last_outcome" TEXT,

    CONSTRAINT "RomanMemoryState_pkey" PRIMARY KEY ("client_id")
);

CREATE INDEX "RomanClientNote_client_id_superseded_at_expires_at_idx" ON "RomanClientNote"("client_id", "superseded_at", "expires_at");

CREATE INDEX "RomanClientNote_source_message_id_idx" ON "RomanClientNote"("source_message_id");

CREATE INDEX "RomanClientNote_superseded_by_id_idx" ON "RomanClientNote"("superseded_by_id");

CREATE UNIQUE INDEX "RomanClientSummary_client_id_period_period_start_key" ON "RomanClientSummary"("client_id", "period", "period_start");

ALTER TABLE "RomanClientNote" ADD CONSTRAINT "RomanClientNote_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "RomanClientNote" ADD CONSTRAINT "RomanClientNote_source_message_id_fkey" FOREIGN KEY ("source_message_id") REFERENCES "RomanMessage"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "RomanClientNote" ADD CONSTRAINT "RomanClientNote_superseded_by_id_fkey" FOREIGN KEY ("superseded_by_id") REFERENCES "RomanClientNote"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "RomanClientSummary" ADD CONSTRAINT "RomanClientSummary_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "RomanMemoryState" ADD CONSTRAINT "RomanMemoryState_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- =====================================================================
-- 2) CHECK constraints: closed sets and lengths
-- =====================================================================
ALTER TABLE "RomanClientNote" ADD CONSTRAINT "RomanClientNote_kind_check" CHECK (
    "kind" IN ('preference', 'schedule', 'household', 'work', 'injury_history', 'goal',
               'equipment', 'diet_like', 'diet_dislike', 'travel', 'other')
);
ALTER TABLE "RomanClientNote" ADD CONSTRAINT "RomanClientNote_key_check" CHECK (char_length("key") BETWEEN 1 AND 120);
ALTER TABLE "RomanClientNote" ADD CONSTRAINT "RomanClientNote_text_check" CHECK (char_length("text") BETWEEN 1 AND 200);
ALTER TABLE "RomanClientNote" ADD CONSTRAINT "RomanClientNote_source_kind_check" CHECK ("source_kind" IN ('roman_chat'));
ALTER TABLE "RomanClientNote" ADD CONSTRAINT "RomanClientNote_superseded_check" CHECK (
    "superseded_by_id" IS NULL OR "superseded_at" IS NOT NULL
);

ALTER TABLE "RomanClientSummary" ADD CONSTRAINT "RomanClientSummary_period_check" CHECK ("period" IN ('day', 'week', 'month'));
ALTER TABLE "RomanClientSummary" ADD CONSTRAINT "RomanClientSummary_text_check" CHECK (char_length("text") BETWEEN 1 AND 1200);

ALTER TABLE "RomanMemoryState" ADD CONSTRAINT "RomanMemoryState_last_outcome_check" CHECK (
    "last_outcome" IS NULL OR "last_outcome" IN ('ok', 'no_consent', 'pool_empty', 'breaker', 'error')
);

-- =====================================================================
-- 3) RLS: service_role only; anon denied; no API-role grant
-- =====================================================================
ALTER TABLE "RomanClientNote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RomanClientNote" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "RomanClientNote" FROM anon, authenticated;

CREATE POLICY "p_romanclientnote_service_role_all" ON "RomanClientNote"
    AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
COMMENT ON POLICY "p_romanclientnote_service_role_all" ON "RomanClientNote" IS
  'Primitive A: the backend writes and reads Roman notes server-side. No client, coach or owner policy.';

CREATE POLICY "p_romanclientnote_anon_deny" ON "RomanClientNote"
    AS RESTRICTIVE FOR ALL TO anon USING (false) WITH CHECK (false);
COMMENT ON POLICY "p_romanclientnote_anon_deny" ON "RomanClientNote" IS
  'RESTRICTIVE deny-all: anon never reads or writes this table.';

ALTER TABLE "RomanClientSummary" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RomanClientSummary" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "RomanClientSummary" FROM anon, authenticated;

CREATE POLICY "p_romanclientsummary_service_role_all" ON "RomanClientSummary"
    AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
COMMENT ON POLICY "p_romanclientsummary_service_role_all" ON "RomanClientSummary" IS
  'Primitive A: the backend writes and reads Roman summaries server-side. No client, coach or owner policy.';

CREATE POLICY "p_romanclientsummary_anon_deny" ON "RomanClientSummary"
    AS RESTRICTIVE FOR ALL TO anon USING (false) WITH CHECK (false);
COMMENT ON POLICY "p_romanclientsummary_anon_deny" ON "RomanClientSummary" IS
  'RESTRICTIVE deny-all: anon never reads or writes this table.';

ALTER TABLE "RomanMemoryState" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RomanMemoryState" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "RomanMemoryState" FROM anon, authenticated;

CREATE POLICY "p_romanmemorystate_service_role_all" ON "RomanMemoryState"
    AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
COMMENT ON POLICY "p_romanmemorystate_service_role_all" ON "RomanMemoryState" IS
  'Primitive A: the memory jobs keep their per-client state server-side. No client, coach or owner policy.';

CREATE POLICY "p_romanmemorystate_anon_deny" ON "RomanMemoryState"
    AS RESTRICTIVE FOR ALL TO anon USING (false) WITH CHECK (false);
COMMENT ON POLICY "p_romanmemorystate_anon_deny" ON "RomanMemoryState" IS
  'RESTRICTIVE deny-all: anon never reads or writes this table.';

RESET lock_timeout;
