const g = require('./guard_extract.js');
const cases = [
 'this.logger.error(`send failed user=${userId}: ${err}`)',
 'this.logger.error(`send failed: ${err}`)',
 'this.logger.error(`send failed user=${userId}: ${error}`)',
 'this.logger.error(`failed ${err.toString()}`)',
 'this.logger.error(`failed ${(err as Error)}`)',
 'this.logger.error(`failed ${inspect(err)}`)',
 'this.logger.error(`failed ${JSON.stringify(error)}`)',
 'this.logger.error(`failed for user=${id}`, err)',
 'this.logger.error(`failed for user=${id}`, err.stack)',
 'this.logger.error(`failed for user=${id}`, error)',
 'this.logger.warn(`failed: ${e instanceof Error ? e.message : e}`)',
 'this.logger.warn(`failed: ${reason}`)',
 'this.logger.warn(`user ${user.fullName}`)',
 'this.logger.warn(`user ${profile.display_name}`)',
 'this.logger.warn(`user ${user.firstName}`)',
 'this.logger.warn(`user ${coachFirstName}`)',
 'this.logger.warn(`to ${recipientAddress}`)',
 'this.logger.warn(`to ${user.mail}`)',
 'this.logger.warn(`to ${addr}`)',
 'this.logger.warn(`q=${q}`)',
 'this.logger.warn(`msg ${message.content}`)',
 'this.logger.warn(`msg ${dto.message}`)',
 'this.logger.warn(`name ${name}`)',
 'this.logger.warn(`name ${c.name}`)',
 'this.logger.warn(`name ${row.name}`)',
 'this.logger.warn(`note ${note}`)',
 'this.logger.warn(`body ${body}`)',
 'this.logger.warn(`x ${error?.message}`)',
 'this.logger.warn(`x ${err?.message ?? STR}`)',
];
for (const s of cases) { const c = g.logCalls(s); console.log(JSON.stringify(g.violations(c[0].code)), s); }
