-- ─────────────────────────────────────────────────────────────────────────────
-- Migration: 20260704000001_coach_brief_cwa_index_concurrent
--
-- WHAT:  Create the (assigned_by_coach_id, approved_by_coach_at) index on
--        ClientWorkoutAssignment that supports the Coach Brief
--        "workouts pending coach approval" query path.
--
-- WHY CONCURRENTLY (Audit #4, P2-1):
--   ClientWorkoutAssignment is a hot, populated production table. A standard
--   CREATE INDEX takes an ACCESS EXCLUSIVE lock for the duration of the index
--   build, which blocks INSERT/UPDATE/DELETE on the entire table. On a large
--   table that can mean tens of seconds to minutes of write downtime — bad
--   enough to cause request timeouts in the assignment flow.
--
--   CREATE INDEX CONCURRENTLY builds the index without blocking writes. It
--   takes longer in wall-clock time and uses more I/O, but only takes a
--   ShareUpdateExclusive lock that does not conflict with normal DML.
--
-- TRANSACTION HANDLING (Prisma 6.19):
--   CREATE INDEX CONCURRENTLY cannot run inside a transaction block. Prisma
--   6.19's migration engine does NOT wrap a migration file in a transaction,
--   so a bare CREATE INDEX CONCURRENTLY runs at the top level as required.
--   The previous COMMIT;/BEGIN; bookend (a Prisma 5-era workaround) actively
--   re-broke this under 6.19 by putting the statement back inside a
--   transaction (SQLSTATE 25001: CREATE INDEX CONCURRENTLY cannot run inside
--   a transaction block). The bookend has been removed accordingly.
--     https://github.com/prisma/prisma/issues/12940
--     https://github.com/prisma/prisma/issues/13672
--
-- WHY IT IS SAFE TO RE-RUN:
--   IF NOT EXISTS makes the CREATE idempotent. If a previous CONCURRENTLY
--   build failed mid-way, Postgres leaves an INVALID index that IF NOT EXISTS
--   will see as already-present. Operators should run:
--     SELECT indexrelid::regclass FROM pg_index WHERE NOT indisvalid;
--   after deploy and DROP INDEX CONCURRENTLY any invalid leftovers before
--   re-running, per Postgres docs.
--
-- INDEX NAME:
--   Named to match Prisma's auto-generated name for
--   @@index([assigned_by_coach_id, approved_by_coach_at]) on
--   ClientWorkoutAssignment (schema.prisma). The full generated name exceeds
--   Postgres's 63-char identifier limit, so Prisma truncates the base and
--   keeps the _idx suffix, yielding
--   ClientWorkoutAssignment_assigned_by_coach_id_approved_by_co_idx. Using
--   this exact name keeps `prisma migrate diff` drift-free.
--
-- ROLLBACK:
--   DROP INDEX CONCURRENTLY IF EXISTS
--     "ClientWorkoutAssignment_assigned_by_coach_id_approved_by_co_idx";
-- ─────────────────────────────────────────────────────────────────────────────

CREATE INDEX CONCURRENTLY IF NOT EXISTS
  "ClientWorkoutAssignment_assigned_by_coach_id_approved_by_co_idx"
  ON "ClientWorkoutAssignment" ("assigned_by_coach_id", "approved_by_coach_at");
