/**
 * bootstrap-test-schema.ts — materialise a Prisma-faithful schema in a
 * throwaway Postgres DB for live integration specs (MWB-2 G9 concurrency proof).
 *
 * Why this exists (Fixer R2, audit P1): the prior hand-rolled minimal DDL in
 * test/rls-mwb2-clone-concurrency.spec.ts drifted from the generated Prisma
 * client (it omitted User.show_on_leaderboard and other columns), so the
 * concurrency spec died at runtime before it could prove the one-commit /
 * one-ConflictException contract. This helper replaces the hand-rolled subset
 * with the FULL canonical schema, generated by Prisma itself.
 *
 * Strategy (Option A — `db push`-equivalent, see fixer report rationale):
 * `npx prisma db push` of the WHOLE schema cannot complete on this repo because
 * a pre-existing, out-of-PR-scope defect makes 12 community_* foreign keys
 * un-implementable: community_* PKs are uuid while User.id is text, so e.g.
 * `community_workspaces_coach_id_fkey (uuid) -> User.id (text)` is rejected with
 * "foreign key constraint ... cannot be implemented / incompatible types". That
 * mismatch lives entirely in the community cluster and never touches the clone
 * path (User, WorkoutProgram, WorkoutPlan, WorkoutPlanExercise,
 * WorkoutPlanRevision, WorkoutProgramRevision).
 *
 * So instead of `prisma db push` (all-or-nothing), we generate the identical
 * DDL Prisma would push via `prisma migrate diff --from-empty
 * --to-schema-datamodel <schema> --script` (canonical, byte-faithful to the
 * generated client) and apply it statement-by-statement, tolerating ONLY the
 * known cross-type community FK failures. ANY other error aborts the bootstrap,
 * so a genuine schema regression on a clone-path table can never be masked.
 */

import { execFileSync } from 'child_process';
import * as path from 'path';
import type { PrismaClient } from '@prisma/client';

const REPO_ROOT = path.resolve(__dirname, '..', '..');
const SCHEMA_PATH = path.join(REPO_ROOT, 'prisma', 'schema.prisma');

/**
 * The only failures we tolerate are the pre-existing community uuid<->text FK
 * mismatches. We match Postgres' wording rather than a constraint allowlist so
 * the tolerance is tied to the *kind* of defect (incompatible FK types), not to
 * a hard-coded list that could rot. Every tolerated statement is logged.
 */
function isToleratedFkError(message: string): boolean {
  const m = message.toLowerCase();
  return (
    m.includes('foreign key constraint') &&
    (m.includes('cannot be implemented') ||
      m.includes('incompatible types'))
  );
}

/**
 * Split the generated SQL into individual statements on top-level semicolons.
 * The Prisma-generated diff emits one statement per logical group, each
 * preceded by a `-- CreateTable` / `-- CreateEnum` / `-- AddForeignKey` comment
 * line and terminated by `;`. There are no dollar-quoted bodies in a
 * from-empty datamodel diff (no functions/DO blocks), so a simple semicolon
 * split is safe. We strip leading `--` comment lines from each chunk rather
 * than discarding the chunk (the comment is the statement's label, not the
 * statement), and drop anything that has no SQL left.
 */
function splitStatements(sql: string): string[] {
  return sql
    .split(/;\s*\n/)
    .map((chunk) =>
      chunk
        .split('\n')
        .filter((line) => !line.trim().startsWith('--'))
        .join('\n')
        .trim(),
    )
    .filter((s) => s.length > 0);
}

/**
 * Generate the canonical full-schema DDL exactly as `prisma db push` would
 * compute it, using the repo's own schema as the source of truth.
 */
export function generateSchemaDdl(): string {
  const out = execFileSync(
    'npx',
    [
      'prisma',
      'migrate',
      'diff',
      '--from-empty',
      '--to-schema-datamodel',
      SCHEMA_PATH,
      '--script',
    ],
    { cwd: REPO_ROOT, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 },
  );
  return out;
}

/**
 * Materialise the full Prisma schema into the connected throwaway DB, then run
 * a runtime guard proving the clone-path models are byte-faithful to the
 * generated client. Throws on any non-tolerated DDL error or a guard failure.
 */
export async function bootstrapTestSchema(prisma: PrismaClient): Promise<void> {
  const ddl = generateSchemaDdl();
  const statements = splitStatements(ddl);

  let applied = 0;
  const tolerated: string[] = [];
  for (const stmt of statements) {
    try {
      await prisma.$executeRawUnsafe(stmt);
      applied += 1;
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      if (isToleratedFkError(message)) {
        // Pre-existing community uuid<->text FK mismatch — out of PR scope and
        // never on the clone path. Tolerated, but logged so it is never silent.
        const head = stmt.replace(/\s+/g, ' ').slice(0, 120);
        tolerated.push(head);
        continue;
      }
      throw new Error(
        `bootstrap-test-schema: unexpected DDL failure (NOT a tolerated ` +
          `community FK mismatch):\n  statement: ${stmt.slice(0, 300)}\n  error: ${message}`,
      );
    }
  }

  if (tolerated.length > 0) {
    // eslint-disable-next-line no-console
    console.warn(
      `[bootstrap-test-schema] applied ${applied} statements; tolerated ` +
        `${tolerated.length} pre-existing community uuid<->text FK mismatch(es) ` +
        `(out of PR scope, never on the clone path):\n  - ` +
        tolerated.join('\n  - '),
    );
  }

  // Runtime guard — fail fast and loud if the clone-path models drifted from
  // the generated client (the exact failure mode this fix exists to kill).
  // A successful select against each table forces Prisma to serialise EVERY
  // column it knows about, so a missing column (e.g. show_on_leaderboard)
  // surfaces here in beforeAll rather than mid-test.
  await prisma.user.findFirst();
  await prisma.workoutProgram.findFirst();
  await prisma.workoutPlan.findFirst();
  await prisma.workoutPlanExercise.findFirst();
  await prisma.workoutPlanRevision.findFirst();
  await prisma.workoutProgramRevision.findFirst();
}
