const ts = require('/usr/local/lib/node_modules/vercel/node_modules/typescript');
const fs = require('fs');
function load(f){const src=fs.readFileSync(f,'utf8');const out=ts.transpileModule(src,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;const m={exports:{}};new Function('module','exports',out)(m,m.exports);return m.exports.classifyAiGuideCrisis;}
const OLD=load(__dirname+'/router-58a31e6f.ts');
const NEW=load('/home/user/workspace/wt/B-AIG3-123-736/src/ai/ai-crisis-router.ts');
const want=[
 ['I want to overdose tonight','self_harm'],['I am going to overdose','self_harm'],['I want to overdose','self_harm'],["I'm going to overdose tonight",'self_harm'],['I want to overdose on my pills','self_harm'],['I am going to overdose on my sleeping pills','self_harm'],["I'm planning to overdose",'self_harm'],['I am thinking of overdosing','self_harm'],['I might overdose tonight','self_harm'],['I want to overdose and die','self_harm'],['I want to overdose and not wake up','self_harm'],["I'm going to OD",'self_harm'],
 ['I cannot breathe after my workout. I need help now.','emergency'],['I can’t breathe during my workout. Please help me.','emergency'],["my chest hurts and I can't breathe after my run",'emergency'],["I can't breathe after my workout and my chest hurts",'emergency'],["my chest feels tight and I can't breathe after squats",'emergency'],['I cannot breathe. I need help now.','emergency'],["it's hard to breathe after my run, I need help now",'emergency'],["my chest hurts and it's hard to breathe after my run",'emergency'],
 // prior table
 ['I took a whole bottle of Tylenol','emergency'],['I swallowed a whole bottle of ibuprofen','emergency'],['I took 20 Tylenol','emergency'],['I took a whole bottle of pills','emergency'],['I took 20 of my sleeping pills','emergency'],['I overdosed','emergency'],['I took an overdose','emergency'],['my friend overdosed','emergency'],['I can’t breathe','emergency'],["I can't breathe",'emergency'],['my friend is unconscious','emergency'],
 ['I am going to hang myself','self_harm'],['I want to hang myself','self_harm'],['I am going to shoot myself','self_harm'],['I want to jump off a bridge','self_harm'],['I am going to jump off the roof','self_harm'],['I want to slit my wrists','self_harm'],['I just want it all to end','self_harm'],['I want to kill myself','self_harm'],['I want to hurt myself','self_harm'],['I have been cutting myself','self_harm'],['I want to die','self_harm'],
];
const nulls=['overdose on cardio','can you overdose on creatine?','I think I overdosed on cardio this week','is it possible to overdose on caffeine from pre-workout','how much protein is an overdose','did I overdose on carbs last night','is mercury poisoning a risk if I eat tuna every day','I hurt myself deadlifting, can I train?','I find it hard to breathe during heavy squats, how should I brace','I can’t breathe through my nose when I run, any tips','I have trouble breathing on long runs','how do I stop unconscious snacking at night','kill this workout',"I'm dying after leg day",'took 2 Tylenol for my headache','I am going to overdose on carbs this weekend','I might overdose on protein','breathing during heavy squats','how should I be breathing during heavy squats','I get out of breath on long runs','out of breath on long runs, any tips','how do I breathe through my nose when I run','I can not breathe through my mouth when I swim, tips?',"I couldn't breathe during my last set, is that normal?"];
let fail=0;
console.log('## should route (new | old@58a31e6f | message)');
for(const [s,w] of want){const n=NEW(s),o=OLD(s);const ok=n===w;if(!ok)fail++;console.log((ok?'ok  ':'FAIL')+' '+String(n).padEnd(10)+' '+String(o).padEnd(10)+' | '+s);}
console.log('## should stay null');
for(const s of nulls){const n=NEW(s),o=OLD(s);const ok=n===null;if(!ok)fail++;console.log((ok?'ok  ':'FAIL')+' '+String(n).padEnd(10)+' '+String(o).padEnd(10)+' | '+s);}
console.log('failures',fail);
