import { IsEmail, IsIn, IsOptional, IsString, MaxLength, MinLength } from 'class-validator';

// SECURITY: DTOs for high-risk auth endpoints that touch the User model and/or
// the `role` field. The global ValidationPipe (src/main.ts) is configured with
// `whitelist: true, forbidNonWhitelisted: true`, so any field not listed here
// is stripped/rejected — preventing mass-assignment on role/coach_id.
// See audit C3/C4.

export class RegisterDto {
  @IsEmail()
  email!: string;

  @IsString()
  @MinLength(8)
  password!: string;

  @IsString()
  @MinLength(1)
  name!: string;

  @IsOptional()
  @IsString()
  phone?: string;
}

export class LoginDto {
  @IsEmail()
  email!: string;

  @IsString()
  password!: string;
}

export class GoogleAuthDto {
  @IsString()
  @MinLength(10)
  token!: string;

  // Optional invite code propagated through the Google OAuth roundtrip. The
  // OAuth provider itself cannot carry it, so the mobile app sends it on the
  // server-side exchange. When present and valid we attach the new user to
  // that coach in the same request (no second /auth/attach-invite-code hop).
  @IsOptional()
  @IsString()
  @MaxLength(32)
  invite_code?: string;
}

// Mobile (#56) calls /auth/attach-invite-code; backend exposes the same
// behavior as /auth/attach-coach-code. Alias DTO so the validation pipe
// accepts the new field name without dropping it as unknown.
export class AttachInviteCodeDto {
  @IsString()
  @MinLength(3)
  @MaxLength(32)
  invite_code!: string;
}

export class SelectRoleDto {
  // Coach elevation via client input is disabled (see auth.service.selectRole).
  // We still accept the field to keep the API contract stable, but only `student`
  // is honored — a `coach` value will be rejected server-side with 403.
  @IsIn(['coach', 'student'])
  role!: 'coach' | 'student';

  // Legacy: previously a fake/unused `coach_code`. Still accepted for API
  // back-compat. If supplied (and `invite_code` is not) it is treated as an
  // invite code and validated the same way — so old clients that somehow send
  // this field aren't silently broken.
  @IsOptional()
  @IsString()
  @MaxLength(32)
  coach_code?: string;

  // Real invite code (e.g. GP-A1B2C3) generated by a coach. Optional — signup
  // still works without one (the user just has no coach until they redeem later).
  @IsOptional()
  @IsString()
  @MaxLength(32)
  invite_code?: string;
}

export class ValidateInviteCodePublicDto {
  @IsString()
  @MinLength(3)
  @MaxLength(32)
  code!: string;
}

export class ForgotPasswordDto {
  @IsEmail()
  email!: string;
}

export class BecomeCoachDto {
  // The user must confirm their password to prevent accidental/CSRF escalation.
  @IsString()
  @MinLength(8)
  password!: string;
}

// Phase 1C: client-side signup that includes a coach invite code in the
// same request. Mobile uses this when the app is launched off a deep
// link with the coach's code already in hand. Behind the
// COACH_CODE_GATE_ENABLED flag the code is REQUIRED; otherwise the
// flow falls back to ordinary register + later attach.
export class SignupWithCodeDto {
  @IsEmail()
  email!: string;

  @IsString()
  @MinLength(8)
  password!: string;

  @IsString()
  @MinLength(1)
  name!: string;

  @IsOptional()
  @IsString()
  phone?: string;

  @IsOptional()
  @IsString()
  @MaxLength(32)
  invite_code?: string;
}
