import {
  IsEmail,
  IsIn,
  IsOptional,
  IsString,
  Matches,
  MaxLength,
  MinLength,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

// SECURITY: DTOs for high-risk auth endpoints that touch the User model and/or
// the `role` field. The global ValidationPipe (src/main.ts) is configured with
// `whitelist: true, forbidNonWhitelisted: true`, so any field not listed here
// is stripped/rejected — preventing mass-assignment on role/coach_id.
// See audit C3/C4.

export class RegisterDto {
  @ApiProperty({ example: 'jane@example.com', format: 'email' })
  @IsEmail()
  email!: string;

  @ApiProperty({ minLength: 8, example: 'correct horse battery staple' })
  @IsString()
  @MinLength(8)
  password!: string;

  @ApiProperty({ example: 'Jane Doe' })
  @IsString()
  @MinLength(1)
  name!: string;

  @ApiPropertyOptional({ example: '+15555550100' })
  @IsOptional()
  @IsString()
  phone?: string;

  @ApiPropertyOptional({ description: 'Signup attribution ref (e.g. importer-extension)' })
  @IsOptional()
  @IsString()
  @MaxLength(64)
  @Matches(/^[a-z0-9_-]+$/, {
    message: 'ref must be lowercase alphanumeric with dashes/underscores',
  })
  ref?: string;
}

export class LoginDto {
  @ApiProperty({ example: 'jane@example.com', format: 'email' })
  @IsEmail()
  email!: string;

  @ApiProperty({ example: 'correct horse battery staple' })
  @IsString()
  password!: string;
}

export class GoogleAuthDto {
  @ApiProperty({
    description: 'Google ID token from the mobile or web SDK.',
    minLength: 10,
  })
  @IsString()
  @MinLength(10)
  token!: string;

  // Optional invite code propagated through the Google OAuth roundtrip. The
  // OAuth provider itself cannot carry it, so the mobile app sends it on the
  // server-side exchange. When present and valid we attach the new user to
  // that coach in the same request (no second /auth/attach-invite-code hop).
  @ApiPropertyOptional({
    description: 'Optional coach invite code attached on the same call.',
    example: 'GP-A1B2C3',
    maxLength: 32,
  })
  @IsOptional()
  @IsString()
  @MaxLength(32)
  invite_code?: string;
}

export class AppleAuthDto {
  @ApiProperty({
    description:
      'Apple identity token (JWT) issued by Sign in with Apple on the mobile or web SDK.',
    minLength: 10,
  })
  @IsString()
  @MinLength(10)
  token!: string;

  // Apple only returns the user's full_name on the FIRST authorization, in the
  // SDK response — never inside the identity token. The mobile app must pass
  // it through on that first call so the server can persist it; subsequent
  // logins omit the field.
  @ApiPropertyOptional({
    description:
      "User's full name from the Apple SDK's first-authorization response. Apple does not include this in the identity token, so mobile must forward it explicitly on first contact.",
    example: 'Jane Doe',
    maxLength: 200,
  })
  @IsOptional()
  @IsString()
  @MaxLength(200)
  full_name?: string;

  // Optional invite code propagated through the Apple OAuth roundtrip. The
  // OAuth provider itself cannot carry it, so the mobile app sends it on the
  // server-side exchange. When present and valid we attach the new user to
  // that coach in the same request (no second /auth/attach-invite-code hop).
  @ApiPropertyOptional({
    description: 'Optional coach invite code attached on the same call.',
    example: 'GP-A1B2C3',
    maxLength: 32,
  })
  @IsOptional()
  @IsString()
  @MaxLength(32)
  invite_code?: string;

  // Raw nonce generated by the mobile client for this Sign in with Apple
  // attempt. Apple embeds sha256(raw_nonce) in the identity token.
  // The server re-hashes and compares before issuing a session.
  // Optional during migration — clients that do not yet send a nonce are
  // accepted but flagged; future enforcement should make this required.
  @ApiPropertyOptional({
    description:
      'Raw nonce (min 16 chars) generated by the mobile SDK for this Apple auth attempt.',
    minLength: 16,
    maxLength: 128,
  })
  @IsOptional()
  @IsString()
  @MinLength(16)
  @MaxLength(128)
  raw_nonce?: string;
}

// Mobile (#56) calls /auth/attach-invite-code; backend exposes the same
// behavior as /auth/attach-coach-code. Alias DTO so the validation pipe
// accepts the new field name without dropping it as unknown.
export class AttachInviteCodeDto {
  @ApiProperty({ example: 'GP-A1B2C3', minLength: 3, maxLength: 32 })
  @IsString()
  @MinLength(3)
  @MaxLength(32)
  invite_code!: string;
}

export class SelectRoleDto {
  // Coach elevation via client input is disabled (see auth.service.selectRole).
  // We still accept the field to keep the API contract stable, but only `student`
  // is honored — a `coach` value will be rejected server-side with 403.
  @ApiProperty({ enum: ['coach', 'student'], example: 'student' })
  @IsIn(['coach', 'student'])
  role!: 'coach' | 'student';

  // Legacy: previously a fake/unused `coach_code`. Still accepted for API
  // back-compat. If supplied (and `invite_code` is not) it is treated as an
  // invite code and validated the same way — so old clients that somehow send
  // this field aren't silently broken.
  @ApiPropertyOptional({
    deprecated: true,
    description: 'Legacy alias of invite_code; prefer invite_code on new clients.',
    maxLength: 32,
  })
  @IsOptional()
  @IsString()
  @MaxLength(32)
  coach_code?: string;

  // Real invite code (e.g. GP-A1B2C3) generated by a coach. Optional — signup
  // still works without one (the user just has no coach until they redeem later).
  @ApiPropertyOptional({ example: 'GP-A1B2C3', maxLength: 32 })
  @IsOptional()
  @IsString()
  @MaxLength(32)
  invite_code?: string;
}

// Public invite-code preview body. Length / format checks are deliberately
// loose here so the controller can return a polished structured 400 (with a
// stable `code: 'invite_code_invalid_format'`) instead of class-validator's
// raw error array. The hard 256-char ceiling is just a payload sanity bound
// to keep the body small; the user-facing format spec lives in the controller
// + /auth/signup-policy and is the single source of truth.
export class ValidateInviteCodePublicDto {
  @ApiProperty({
    description: 'Invite code to preview. Format-validated server-side.',
    example: 'GP-A1B2C3',
    maxLength: 256,
  })
  @IsString()
  @MaxLength(256)
  code!: string;
}

export class ForgotPasswordDto {
  @ApiProperty({ example: 'jane@example.com', format: 'email' })
  @IsEmail()
  email!: string;
}

export class BecomeCoachDto {
  // The user must confirm their password to prevent accidental/CSRF escalation.
  @ApiProperty({
    description: 'Current password — required to prevent accidental escalation.',
    minLength: 8,
  })
  @IsString()
  @MinLength(8)
  password!: string;
}

// Phase 1C: client-side signup that includes a coach invite code in the
// same request. Mobile uses this when the app is launched off a deep
// link with the coach's code already in hand. Behind the
// COACH_CODE_GATE_ENABLED flag the code is REQUIRED; otherwise the
// flow falls back to ordinary register + later attach.
export class SignupWithCodeDto {
  @ApiProperty({ example: 'jane@example.com', format: 'email' })
  @IsEmail()
  email!: string;

  @ApiProperty({ minLength: 8 })
  @IsString()
  @MinLength(8)
  password!: string;

  @ApiProperty({ example: 'Jane Doe' })
  @IsString()
  @MinLength(1)
  name!: string;

  @ApiPropertyOptional({ example: '+15555550100' })
  @IsOptional()
  @IsString()
  phone?: string;

  @ApiPropertyOptional({
    description: 'Required when COACH_CODE_GATE_ENABLED=true; otherwise optional.',
    example: 'GP-A1B2C3',
    maxLength: 32,
  })
  @IsOptional()
  @IsString()
  @MaxLength(32)
  invite_code?: string;

  @ApiPropertyOptional({ description: 'Signup attribution ref (e.g. importer-extension)' })
  @IsOptional()
  @IsString()
  @MaxLength(64)
  @Matches(/^[a-z0-9_-]+$/, {
    message: 'ref must be lowercase alphanumeric with dashes/underscores',
  })
  ref?: string;
}

// Extension token refresh: proxies Supabase refreshSession(refresh_token) and
// returns the rotated pair. The Chrome importer extension calls this when its
// short-lived Supabase access token expires. No backend-minted tokens — the
// refresh token is Supabase's and Supabase owns rotation + revocation.
export class ExtensionRefreshDto {
  @ApiProperty({ description: 'Supabase refresh token issued by /auth/extension/login' })
  @IsString()
  @MinLength(1)
  @MaxLength(4096)
  refresh_token!: string;
}

// 200 body: the rotated Supabase session the extension stores. expires_in /
// expires_at are Supabase's own numeric fields (seconds / unix-seconds) and are
// passed through verbatim (expires_at may be absent on some Supabase responses).
export class ExtensionRefreshResult {
  @ApiProperty({ description: 'Rotated Supabase access token.' })
  access_token!: string;

  @ApiProperty({ description: 'Rotated Supabase refresh token.' })
  refresh_token!: string;

  @ApiProperty({ description: 'Access-token lifetime in seconds.', example: 3600 })
  expires_in!: number;

  @ApiPropertyOptional({
    description: 'Absolute expiry as a unix timestamp (seconds).',
    example: 1_752_086_400,
  })
  expires_at?: number;
}

// First-gym bootstrap: creates the very first owner-role user on a fresh
// instance. Gated by BOOTSTRAP_SECRET env var AND a "no existing owners"
// precondition, so it cannot be used to escalate after launch.
export class BootstrapOwnerDto {
  @ApiProperty({ example: 'founder@example.com', format: 'email' })
  @IsEmail()
  email!: string;

  @ApiProperty({ minLength: 8 })
  @IsString()
  @MinLength(8)
  password!: string;

  @ApiProperty({ example: 'Founder Name' })
  @IsString()
  @MinLength(1)
  name!: string;

  @ApiProperty({
    description:
      'Shared secret matching BOOTSTRAP_SECRET on the server. Unset the env var after first use.',
    minLength: 16,
  })
  @IsString()
  @MinLength(16)
  bootstrap_secret!: string;
}

/** Body for POST /auth/recent-auth-token (Phase 10 re-auth hardening).
 *
 * Accepts EITHER:
 *   (a) password                       — for email/password users
 *   (b) provider_token + provider      — for OAuth-only users (Google/Apple).
 *
 * (b) exists because OAuth-only users have no password on file. Forcing them
 * to provide one would lock them out of account deletion entirely (GDPR /
 * compliance regression — see PR #167 audit).
 *
 * The DTO does not enforce "exactly one" — the service rejects the case
 * where neither is provided with a structured 400. This keeps the DTO
 * forward-compatible with future re-auth methods (e.g. WebAuthn / passkeys).
 */
export class IssueRecentAuthTokenDto {
  @ApiPropertyOptional({
    description:
      "The user's current password — verified against Supabase before the token is issued. Required for email/password users.",
    minLength: 1,
  })
  @IsOptional()
  @IsString()
  @MinLength(1)
  password?: string;

  @ApiPropertyOptional({
    description:
      'A fresh provider-issued identity token used by OAuth-only users to prove recent auth. The token must have been issued within RECENT_AUTH_TTL_MS (default 5 minutes). ' +
      'For provider=google: requires a fresh Google ID token issued to the configured GOOGLE_CLIENT_ID(S) audience — NOT a Google OAuth access token, NOT a Supabase session JWT. ' +
      'For provider=apple: requires a fresh Apple identity token issued by Sign in with Apple. ' +
      'Supabase access tokens and Google OAuth access tokens are explicitly rejected: the verifier pins issuer + audience against the provider JWKS, so only a real provider-issued ID/identity token will pass.',
    minLength: 10,
  })
  @IsOptional()
  @IsString()
  @MinLength(10)
  provider_token?: string;

  @ApiPropertyOptional({
    description: 'Provider for provider_token. Required when provider_token is provided.',
    enum: ['google', 'apple'],
  })
  @IsOptional()
  @IsIn(['google', 'apple'])
  provider?: 'google' | 'apple';
}
