import { IsEmail, IsIn, IsOptional, IsString, MaxLength, MinLength } from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

// SECURITY: DTOs for high-risk auth endpoints that touch the User model and/or
// the `role` field. The global ValidationPipe (src/main.ts) is configured with
// `whitelist: true, forbidNonWhitelisted: true`, so any field not listed here
// is stripped/rejected — preventing mass-assignment on role/coach_id.
// See audit C3/C4.

export class RegisterDto {
  @ApiProperty({ example: 'jane@example.com', format: 'email' })
  @IsEmail()
  email!: string;

  @ApiProperty({ minLength: 8, example: 'correct horse battery staple' })
  @IsString()
  @MinLength(8)
  password!: string;

  @ApiProperty({ example: 'Jane Doe' })
  @IsString()
  @MinLength(1)
  name!: string;

  @ApiPropertyOptional({ example: '+15555550100' })
  @IsOptional()
  @IsString()
  phone?: string;
}

export class LoginDto {
  @ApiProperty({ example: 'jane@example.com', format: 'email' })
  @IsEmail()
  email!: string;

  @ApiProperty({ example: 'correct horse battery staple' })
  @IsString()
  password!: string;
}

export class GoogleAuthDto {
  @ApiProperty({
    description: 'Google ID token from the mobile or web SDK.',
    minLength: 10,
  })
  @IsString()
  @MinLength(10)
  token!: string;

  // Optional invite code propagated through the Google OAuth roundtrip. The
  // OAuth provider itself cannot carry it, so the mobile app sends it on the
  // server-side exchange. When present and valid we attach the new user to
  // that coach in the same request (no second /auth/attach-invite-code hop).
  @ApiPropertyOptional({
    description: 'Optional coach invite code attached on the same call.',
    example: 'GP-A1B2C3',
    maxLength: 32,
  })
  @IsOptional()
  @IsString()
  @MaxLength(32)
  invite_code?: string;
}

// Mobile (#56) calls /auth/attach-invite-code; backend exposes the same
// behavior as /auth/attach-coach-code. Alias DTO so the validation pipe
// accepts the new field name without dropping it as unknown.
export class AttachInviteCodeDto {
  @ApiProperty({ example: 'GP-A1B2C3', minLength: 3, maxLength: 32 })
  @IsString()
  @MinLength(3)
  @MaxLength(32)
  invite_code!: string;
}

export class SelectRoleDto {
  // Coach elevation via client input is disabled (see auth.service.selectRole).
  // We still accept the field to keep the API contract stable, but only `student`
  // is honored — a `coach` value will be rejected server-side with 403.
  @ApiProperty({ enum: ['coach', 'student'], example: 'student' })
  @IsIn(['coach', 'student'])
  role!: 'coach' | 'student';

  // Legacy: previously a fake/unused `coach_code`. Still accepted for API
  // back-compat. If supplied (and `invite_code` is not) it is treated as an
  // invite code and validated the same way — so old clients that somehow send
  // this field aren't silently broken.
  @ApiPropertyOptional({
    deprecated: true,
    description: 'Legacy alias of invite_code; prefer invite_code on new clients.',
    maxLength: 32,
  })
  @IsOptional()
  @IsString()
  @MaxLength(32)
  coach_code?: string;

  // Real invite code (e.g. GP-A1B2C3) generated by a coach. Optional — signup
  // still works without one (the user just has no coach until they redeem later).
  @ApiPropertyOptional({ example: 'GP-A1B2C3', maxLength: 32 })
  @IsOptional()
  @IsString()
  @MaxLength(32)
  invite_code?: string;
}

// Public invite-code preview body. Length / format checks are deliberately
// loose here so the controller can return a polished structured 400 (with a
// stable `code: 'invite_code_invalid_format'`) instead of class-validator's
// raw error array. The hard 256-char ceiling is just a payload sanity bound
// to keep the body small; the user-facing format spec lives in the controller
// + /auth/signup-policy and is the single source of truth.
export class ValidateInviteCodePublicDto {
  @ApiProperty({
    description: 'Invite code to preview. Format-validated server-side.',
    example: 'GP-A1B2C3',
    maxLength: 256,
  })
  @IsString()
  @MaxLength(256)
  code!: string;
}

export class ForgotPasswordDto {
  @ApiProperty({ example: 'jane@example.com', format: 'email' })
  @IsEmail()
  email!: string;
}

export class BecomeCoachDto {
  // The user must confirm their password to prevent accidental/CSRF escalation.
  @ApiProperty({
    description: 'Current password — required to prevent accidental escalation.',
    minLength: 8,
  })
  @IsString()
  @MinLength(8)
  password!: string;
}

// Phase 1C: client-side signup that includes a coach invite code in the
// same request. Mobile uses this when the app is launched off a deep
// link with the coach's code already in hand. Behind the
// COACH_CODE_GATE_ENABLED flag the code is REQUIRED; otherwise the
// flow falls back to ordinary register + later attach.
export class SignupWithCodeDto {
  @ApiProperty({ example: 'jane@example.com', format: 'email' })
  @IsEmail()
  email!: string;

  @ApiProperty({ minLength: 8 })
  @IsString()
  @MinLength(8)
  password!: string;

  @ApiProperty({ example: 'Jane Doe' })
  @IsString()
  @MinLength(1)
  name!: string;

  @ApiPropertyOptional({ example: '+15555550100' })
  @IsOptional()
  @IsString()
  phone?: string;

  @ApiPropertyOptional({
    description:
      'Required when COACH_CODE_GATE_ENABLED=true; otherwise optional.',
    example: 'GP-A1B2C3',
    maxLength: 32,
  })
  @IsOptional()
  @IsString()
  @MaxLength(32)
  invite_code?: string;
}
