name: Fly Secrets List (operator)

on:
  workflow_dispatch:
    inputs:
      app:
        description: Fly app name
        required: true

jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: List secret names
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl secrets list --app "${{ github.event.inputs.app }}"
